In [16]:
import numpy as np 
import pandas as pd

In [17]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [18]:
data = pd.read_csv('../Dataset/gurgaon_properties.csv')
data.sample(5)

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
2856,1 BHK Flat in Palam Vihar,flat,bestech park view residency,0.55,8461.0,650.0,Super Built up area 650(60.39 sq.m.),1,1,2,na,"Palam Vihar, Gurgaon, Haryana",7.0,North,5 to 10 Year Old,"['Dwarka Sector 21 Metro Station', 'HUDA Marke...",Residential apartment for sell.Located in pala...,NaN,"['Lift(s)', 'Swimming Pool', 'Park', 'Visitor ...","['Management4 out of 5', 'Green Area5 out of 5..."
1946,5 Bedroom House for sale in Sector 56 Gurgaon,house,huda sector-56 gurgaon,3.60,24845.0,1449.0,Plot area 161(134.62 sq.m.),5,5,3+,others,"265, Sector 56 Gurgaon, Gurgaon, Haryana",3.0,North-East,5 to 10 Year Old,"['Iffco chowk metro station', 'Mg road metro s...","161 yard 2 5 story built up house ,nearby mark...","['10 Fan', '5 Wardrobe', 'No AC', 'No Bed', 'N...","['Feng Shui / Vaastu Compliant', 'Maintenance ...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
2379,4 BHK Flat in Sector 56 Gurgaon,flat,the lions cghs,2.05,9534.0,2150.0,Super Built up area 2150(199.74 sq.m.)Built Up...,4,4,3,"servant room,others","Sector 56 Gurgaon, Gurgaon, Haryana",7.0,West,1 to 5 Year Old,"['Sector metro station', 'Sector metro station...",This beautiful 4 bhk flat in sector 56 gurgaon...,"['4 Wardrobe', '4 Fan', '1 Exhaust Fan', '4 Ge...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
2337,3 BHK Flat in Sector 112 Gurgaon,flat,experion windchants,4.75,12622.0,3763.0,Super Built up area 3763(349.59 sq.m.),3,5,3+,servant room,"Sector 112 Gurgaon, Gurgaon, Haryana",4.0,West,1 to 5 Year Old,"['Ansal Plaza', 'Dwaraka Expressway', 'First S...",Experionwindchantsprice\nExperionwindchantsvil...,"['1 Water Purifier', '5 Geyser', '1 Chimney', ...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Green Area5 out of 5', 'Construction5 out of..."
2720,2 BHK Flat in Sector 106 Gurgaon,flat,paras dews,0.92,6642.0,1385.0,Super Built up area 1385(128.67 sq.m.)Built Up...,2,2,3+,na,"Sector 106 Gurgaon, Gurgaon, Haryana",2.0,East,1 to 5 Year Old,"['MG Road Metro Station', 'NeoSquare Shopping ...",This beautiful 2 bhk flat in sector 106 gurgao...,"['1 AC', 'No Bed', 'No Chimney', 'No Curtains'...","['Centrally Air Conditioned', 'Water purifier'...",NaN

In [19]:
# Identify columns with 'string' dtype
str_cols = data.select_dtypes(include='string').columns

# Convert them to object
data[str_cols] = data[str_cols].astype('object')

In [20]:
data.shape

(3961, 20)

In [21]:
data.duplicated().sum()

np.int64(0)

In [22]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 3961 entries, 0 to 3960
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    3961 non-null   object
 1   property_type    3961 non-null   object
 2   society          3960 non-null   object
 3   price            3941 non-null   float64
 4   price_per_sqft   3941 non-null   float64
 5   area             3941 non-null   float64
 6   areaWithType     3961 non-null   object
 7   bedRoom          3961 non-null   int64
 8   bathroom         3961 non-null   int64
 9   balcony          3961 non-null   object
 10  additionalRoom   3961 non-null   object
 11  address          3950 non-null   object
 12  floorNum         3940 non-null   float64
 13  facing           2784 non-null   object
 14  agePossession    3960 non-null   object
 15  nearbyLocations  3754 non-null   object
 16  description      3961 non-null   object
 17  furnishDetails   2929 non-null   object
 18  features         3252 non-null   object
 19  rating           3511 non-null   object
dtypes: float64(4), int64(2), object(14)
memory usage: 619.0+ KB

In [23]:
data.isnull().sum()

property_name         0
property_type         0
society               1
price                20
price_per_sqft       20
area                 20
areaWithType          0
bedRoom               0
bathroom              0
balcony               0
additionalRoom        0
address              11
floorNum             21
facing             1177
agePossession         1
nearbyLocations     207
description           0
furnishDetails     1032
features            709
rating              450
dtype: int64

In [24]:
data.head()

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,3 BHK Flat in Sector 76 Gurgaon,flat,whiteland blissville,1.92,11794.0,1628.0,Built Up area: 1628 (151.25 sq.m.),3,3,2,na,"Sector 76, Delhi Gurgaon Expressway, Sector 76...",3.0,NaN,undefined,"['Huda Metro Station', 'Vatika City Centre', '...",Best in class property available at sector 76 ...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,NaN
1,3 BHK Flat in Sector 54 Gurgaon,flat,dlf park place,4.85,30180.0,1607.0,Super Built up area 1983(184.23 sq.m.)Built Up...,3,4,3+,servant room,"H 6, Sector 54 Gurgaon, Gurgaon, Haryana",6.0,North,5 to 10 Year Old,"['Sector 53-54 Metro Station', 'Sector 54 Chow...",Dlf park place is one of gurgaon's most sought...,"['1 Water Purifier', '9 Fan', '1 Fridge', '4 G...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area5 out of 5', 'Construction5 out of..."
2,3 BHK Flat in Sector 37D Gurgaon,flat,signature global city 37d ph 2,1.35,9375.0,1440.0,Carpet area: 1440 (133.78 sq.m.),3,3,3+,pooja room,"Sector 37D Gurgaon, Gurgaon, Haryana",3.0,NaN,Mar 2024,"['Dwarka Expressway', 'Pataudi Road', 'Euro In...",The property has terrace with the same. Beauti...,[],"['Power Back-up', 'Lift(s)', 'Swimming Pool', ...","['Environment4 out of 5', 'Lifestyle4 out of 5..."
3,2 BHK Flat in Sector 95 Gurgaon,flat,sidhartha ncr one,0.55,5556.0,990.0,Built Up area: 990 (91.97 sq.m.)Carpet area: 9...,2,2,3,na,"Sector 95,gurgaon, Sector 95 Gurgaon, Gurgaon,...",15.0,North-East,undefined,NaN,"2 bath, semi-Furnished, 15th floor (Of 20), ov...","['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,"['Environment4 out of 5', 'Safety4.5 out of 5'..."
4,2 BHK Flat in Sector 91 Gurgaon,flat,tarc maceo,0.96,5413.0,1774.0,Super Built up area 1404(130.44 sq.m.),2,2,3+,na,"Sector 91 Gurgaon, Gurgaon, Haryana",8.0,East,5 to 10 Year Old,"['Manish Gallexie 91', 'Dwarka Expressway', 'R...",I want to sell my 2 bhk apartment. Its semi fu...,"['2 Wardrobe', '4 Fan', '2 Geyser', '11 Light'...","['Security / Fire Alarm', 'Intercom Facility',...","['Green Area5 out of 5', 'Construction4 out of..."

In [25]:
# Added Sector column
data.insert(loc=3,column='sector',value = data['property_name'].str.split('in').str.get(1).str.replace('Gurgaon','').str.strip())

In [26]:
data.head()

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,3 BHK Flat in Sector 76 Gurgaon,flat,whiteland blissville,Sector 76,1.92,11794.0,1628.0,Built Up area: 1628 (151.25 sq.m.),3,3,2,na,"Sector 76, Delhi Gurgaon Expressway, Sector 76...",3.0,NaN,undefined,"['Huda Metro Station', 'Vatika City Centre', '...",Best in class property available at sector 76 ...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,NaN
1,3 BHK Flat in Sector 54 Gurgaon,flat,dlf park place,Sector 54,4.85,30180.0,1607.0,Super Built up area 1983(184.23 sq.m.)Built Up...,3,4,3+,servant room,"H 6, Sector 54 Gurgaon, Gurgaon, Haryana",6.0,North,5 to 10 Year Old,"['Sector 53-54 Metro Station', 'Sector 54 Chow...",Dlf park place is one of gurgaon's most sought...,"['1 Water Purifier', '9 Fan', '1 Fridge', '4 G...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area5 out of 5', 'Construction5 out of..."
2,3 BHK Flat in Sector 37D Gurgaon,flat,signature global city 37d ph 2,Sector 37D,1.35,9375.0,1440.0,Carpet area: 1440 (133.78 sq.m.),3,3,3+,pooja room,"Sector 37D Gurgaon, Gurgaon, Haryana",3.0,NaN,Mar 2024,"['Dwarka Expressway', 'Pataudi Road', 'Euro In...",The property has terrace with the same. Beauti...,[],"['Power Back-up', 'Lift(s)', 'Swimming Pool', ...","['Environment4 out of 5', 'Lifestyle4 out of 5..."
3,2 BHK Flat in Sector 95 Gurgaon,flat,sidhartha ncr one,Sector 95,0.55,5556.0,990.0,Built Up area: 990 (91.97 sq.m.)Carpet area: 9...,2,2,3,na,"Sector 95,gurgaon, Sector 95 Gurgaon, Gurgaon,...",15.0,North-East,undefined,NaN,"2 bath, semi-Furnished, 15th floor (Of 20), ov...","['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,"['Environment4 out of 5', 'Safety4.5 out of 5'..."
4,2 BHK Flat in Sector 91 Gurgaon,flat,tarc maceo,Sector 91,0.96,5413.0,1774.0,Super Built up area 1404(130.44 sq.m.),2,2,3+,na,"Sector 91 Gurgaon, Gurgaon, Haryana",8.0,East,5 to 10 Year Old,"['Manish Gallexie 91', 'Dwarka Expressway', 'R...",I want to sell my 2 bhk apartment. Its semi fu...,"['2 Wardrobe', '4 Fan', '2 Geyser', '11 Light'...","['Security / Fire Alarm', 'Intercom Facility',...","['Green Area5 out of 5', 'Construction4 out of..."

In [28]:
data['sector'] = data['sector'].str.lower()
data.head()

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,3 BHK Flat in Sector 76 Gurgaon,flat,whiteland blissville,sector 76,1.92,11794.0,1628.0,Built Up area: 1628 (151.25 sq.m.),3,3,2,na,"Sector 76, Delhi Gurgaon Expressway, Sector 76...",3.0,NaN,undefined,"['Huda Metro Station', 'Vatika City Centre', '...",Best in class property available at sector 76 ...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,NaN
1,3 BHK Flat in Sector 54 Gurgaon,flat,dlf park place,sector 54,4.85,30180.0,1607.0,Super Built up area 1983(184.23 sq.m.)Built Up...,3,4,3+,servant room,"H 6, Sector 54 Gurgaon, Gurgaon, Haryana",6.0,North,5 to 10 Year Old,"['Sector 53-54 Metro Station', 'Sector 54 Chow...",Dlf park place is one of gurgaon's most sought...,"['1 Water Purifier', '9 Fan', '1 Fridge', '4 G...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area5 out of 5', 'Construction5 out of..."
2,3 BHK Flat in Sector 37D Gurgaon,flat,signature global city 37d ph 2,sector 37d,1.35,9375.0,1440.0,Carpet area: 1440 (133.78 sq.m.),3,3,3+,pooja room,"Sector 37D Gurgaon, Gurgaon, Haryana",3.0,NaN,Mar 2024,"['Dwarka Expressway', 'Pataudi Road', 'Euro In...",The property has terrace with the same. Beauti...,[],"['Power Back-up', 'Lift(s)', 'Swimming Pool', ...","['Environment4 out of 5', 'Lifestyle4 out of 5..."
3,2 BHK Flat in Sector 95 Gurgaon,flat,sidhartha ncr one,sector 95,0.55,5556.0,990.0,Built Up area: 990 (91.97 sq.m.)Carpet area: 9...,2,2,3,na,"Sector 95,gurgaon, Sector 95 Gurgaon, Gurgaon,...",15.0,North-East,undefined,NaN,"2 bath, semi-Furnished, 15th floor (Of 20), ov...","['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,"['Environment4 out of 5', 'Safety4.5 out of 5'..."
4,2 BHK Flat in Sector 91 Gurgaon,flat,tarc maceo,sector 91,0.96,5413.0,1774.0,Super Built up area 1404(130.44 sq.m.),2,2,3+,na,"Sector 91 Gurgaon, Gurgaon, Haryana",8.0,East,5 to 10 Year Old,"['Manish Gallexie 91', 'Dwarka Expressway', 'R...",I want to sell my 2 bhk apartment. Its semi fu...,"['2 Wardrobe', '4 Fan', '2 Geyser', '11 Light'...","['Security / Fire Alarm', 'Intercom Facility',...","['Green Area5 out of 5', 'Construction4 out of..."

In [29]:
data['sector'].value_counts()

sector
sohna                                                        163
sector 102                                                   113
sector 85                                                    110
sector 92                                                    104
sector 69                                                     94
sector 81                                                     90
sector 90                                                     90
sector 65                                                     90
sector 109                                                    88
sector 79                                                     80
sector 83                                                     69
sector 37d                                                    68
sector 86                                                     67
sector 104                                                    66
sector 107                                                    60
sector 108                                                    59
sector 95                                                     57
sector 56                                                     57
sector 48                                                     56
sector 89                                                     56
sector 70a                                                    54
sector 37c                                                    53
nirvana country                                               53
sector 70                                                     53
sector-33 sohna                                               51
sector 84                                                     51
palam vihar                                                   50
sector 67                                                     48
sector 66                                                     46
sector 103                                                    45
dlf phase 1                                                   43
dlf phase 2                                                   43
sector 113                                                    43
sector 82                                                     42
sector 61                                                     42
sector 106                                                    38
sector 49                                                     36
sector 99a                                                    32
sushant lok phase 1                                           31
sector 68                                                     30
sector 72                                                     29
sector 77                                                     29
sector 54                                                     27
sector 71                                                     27
laxman vihar                                                  27
dlf phase 4                                                   26
sector 112                                                    24
sector 88a                                                    23
sector 33                                                     23
sector 111                                                    22
sector 67a                                                    22
dlf phase 3                                                   22
sector 22                                                     20
sector 82a                                                    20
sector 78                                                     19
sector 74                                                     18
sector 63a                                                    18
sector 91                                                     17
sector 62                                                     17
sushant lok phase 3                                           16
sector 99                                                     16
sector 110                                                    16
sector 63                                                     15
sector 60                                                     15
sector 14                                                     15
sector 76                                                     14
sector 1 imt manesar                                          14
dlf phase 5                                                   14
rajendra park                                                 14
sector 3                                                      14
sector 53                                                     14
gwal pahari                                                   14
sector 52                                                     14
sector 46                                                     13
laxman vihar phase 2                                          13
sector 36a                                                    13
sector 39                                                     12
sector 93                                                     12
sector 50                                                     12
sohna road                                                    12
sector 38                                                     12
uppals southend                                               12
sector 31                                                     12
sector 47                                                     11
sector 9a                                                     11
ashok vihar phase 3 extension                                 11
sector 1a imt manesar                                         10
sector 7                                                      10
sector 4                                                       9
south city 1                                                   9
sector 95a                                                     9
sector 55                                                      9
ashok vihar phase 2                                            9
palam vihar extension                                          8
mehrauli  road                                                 8
sector 43                                                      8
dwarka expressway                                              8
sector 89 a                                                    8
sector 10a                                                     8
sector 57                                                      8
malibu town                                                    8
sector 59                                                      8
sector 40                                                      8
c block sushant lok phase 1                                    8
sector 58                                                      7
sector 11                                                      7
sector 36 sohna                                                7
new colony                                                     7
sector 26                                                      7
surat nagar 1                                                  7
mianwali colony                                                7
sector 51                                                      7
ashok vihar                                                    6
sector 1                                                       6
rajiv nagar                                                    6
sector 5                                                       6
jyoti park                                                     6
jacobpura                                                      6
arjun nagar                                                    5
new palam vihar                                                5
sushant lok phase 2                                            5
sector 9                                                       5
dayanand colony                                                5
sector 28                                                      5
ansal plaza                                                    5
manesar                                                        5
subhash nagar                                                  5
sector 80                                                      5
sector 30                                                      5
greenwood city                                                 5
sector 105                                                     5
chakkarpur                                                     5
sector 2                                                       5
sector 23a                                                     5
saraswati vihar                                                5
sector 6                                                       4
sector 17                                                      4
new                                                            4
ravi nagar                                                     4
dharam colony                                                  4
sector 3a                                                      4
madanpuri                                                      4
sector 12                                                      4
sector 12a                                                     4
devilal colony                                                 4
adarsh nagar                                                   4
sector 36                                                      4
baldev nagar                                                   4
bhim nagar                                                     4
shivaji nagar                                                  4
sector 45                                                      4
surya vihar                                                    4
garhi harsaru                                                  4
krishna colony                                                 4
bhondsi                                                        4
vishnu garden                                                  4
suncity                                                        4
imt manesar                                                    4
shivpuri                                                       4
valley view estate                                             4
sector 73                                                      3
sector 17b                                                     3
sector 17a                                                     3
sector 23                                                      3
sector 110 a                                                   3
mg road                                                        3
prem nagar                                                     3
sector 88b                                                     3
sector 8                                                       3
gandhi nagar                                                   3
sector 15                                                      3
b block sushant lok phase 1                                    3
laxmi garden                                                   3
a block sushant lok phase 1                                    3
sector 27                                                      3
maruti kunj                                                    3
patel nagar                                                    3
shakti nagar                                                   3
golf course road                                               2
bhawani enclave                                                2
sector 32                                                      2
ambience island                                                2
shankar vihar                                                  2
new palam vihar phase 2                                        2
west rajiv nagar                                               2
nars                                                           2
new basti                                                      2
block a surya vihar                                            2
golf course ext road                                           2
sector 15 part 2                                               2
sector 21                                                      2
pratap nagar                                                   2
sector-2 sohna                                                 2
sector-11 sohna                                                2
sispal vihar                                                   2
, delhi ncr                                                    2
mayfield garden                                                2
rajiv chowk                                                    2
surat nagar phase 2                                            2
bissar                                                         2
mohan nagar                                                    2
sector 24                                                      2
sushant lok                                                    2
farukhnagar                                                    2
surat nagar                                                    2
faridabad road                                                 2
sector 41                                                      2
manohar nagar                                                  2
rosewood                                                       2
hira nagar                                                     2
new palam vihar phase 1                                        2
iffco chowk                                                    2
acharya puri                                                   2
lajpat nagar                                                   2
daulatabad                                                     2
sector 15 part 1                                               2
shanti nagar                                                   2
sohna  road                                                    2
sheetla colony                                                 2
samaspur                                                       2
gopal nagar, garhi ghasita, sonipat                            1
kanahi                                                         1
urban estate, sector 5                                         1
ashok vihar phase 3                                            1
saraswati enclave                                              1
lucknow                                                        1
tekchand nagar                                                 1
begampur khatola                                               1
laxmna vihar, phase 2                                          1
bhimgarh kheri phase 3                                         1
ravi nager basai road                                          1
sector 9b                                                      1
sector 17c                                                     1
ram nagar                                                      1
civil l                                                        1
sec 3 bhim vihar part 1 bhimgher kheri                         1
sector 42                                                      1
sector 21a faridabad                                           1
laxman vihar, railway road,                                    1
near khandsa road                                              1
new jyoti park                                                 1
hsiidc plot sector 1 imt manesar                               1
near pataudi chowk                                             1
rattan garden                                                  1
mahavir pura                                                   1
part 3 sector 5                                                1
sai kunj                                                       1
g block dlf city phase 1                                       1
damdma                                                         1
anand garden, sector-105                                       1
sector 37b                                                     1
jacobpura near sadar bazar                                     1
sector 37a                                                     1
garauli kalan                                                  1
near nand hospital                                             1
alipur                                                         1
carterpuri village                                             1
sector-5 sheetla colony                                        1
near sector 1 market                                           1
devi lal colony gali no 12 gurgaon nr omkar public school      1
om nagar                                                       1
sadar bazar                                                    1
shivji park colony                                             1
block h ashok vihar phase iii extension                        1
sector 13                                                      1
nirvana country pocket h                                       1
saroop garden rajendra park                                    1
godrej aria , sector 79 ,                                      1
kheri                                                          1
naharpur rupa                                                  1
mahalaxmi garden, rajendra place                               1
ats marigold                                                   1
bptp                                                           1
park view                                                      1
rajiv colony                                                   1
vir nagar                                                      1
sultanpur                                                      1
ashok vihar phase i                                            1
heritage city                                                  1
udyog vihar phase 1                                            1
dhankot                                                        1
huda saraswati vihar                                           1
khandsa                                                        1
block g sector-57                                              1
jat colony,fazilpur/taj nagar road                             1
south city                                                     1
hno 13 sagar enclave sura                                      1
sector 5 chowk                                                 1
sector-5 sohna                                                 1
sector-7 hous                                                  1
new colony, sector 7                                           1
ansal's palam vihar                                            1
cyber city                                                     1
v block dlf phase 3                                            1
b1 block sector 57                                             1
sector 4 urban estate                                          1
pataudi road                                                   1
near euro                                                      1
old delhi road, opp sector-14                                  1
sector-35 sohna                                                1
bhora kalan                                                    1
Name: count, dtype: int64

In [30]:
data['sector'] = data['sector'].str.replace('dharam colony','sector 12')
data['sector'] = data['sector'].str.replace('krishna colony','sector 7')
data['sector'] = data['sector'].str.replace('suncity','sector 54')
data['sector'] = data['sector'].str.replace('prem nagar','sector 13')
data['sector'] = data['sector'].str.replace('mg road','sector 28')
data['sector'] = data['sector'].str.replace('gandhi nagar','sector 28')
data['sector'] = data['sector'].str.replace('laxmi garden','sector 11')
data['sector'] = data['sector'].str.replace('shakti nagar','sector 11')

data['sector'] = data['sector'].str.replace('baldev nagar','sector 7')
data['sector'] = data['sector'].str.replace('shivpuri','sector 7')
data['sector'] = data['sector'].str.replace('garhi harsaru','sector 17')
data['sector'] = data['sector'].str.replace('imt manesar','manesar')
data['sector'] = data['sector'].str.replace('adarsh nagar','sector 12')
data['sector'] = data['sector'].str.replace('shivaji nagar','sector 11')
data['sector'] = data['sector'].str.replace('bhim nagar','sector 6')
data['sector'] = data['sector'].str.replace('madanpuri','sector 7')

data['sector'] = data['sector'].str.replace('saraswati vihar','sector 28')
data['sector'] = data['sector'].str.replace('arjun nagar','sector 8')
data['sector'] = data['sector'].str.replace('ravi nagar','sector 9')
data['sector'] = data['sector'].str.replace('vishnu garden','sector 105')
data['sector'] = data['sector'].str.replace('bhondsi','sector 11')
data['sector'] = data['sector'].str.replace('surya vihar','sector 21')
data['sector'] = data['sector'].str.replace('devilal colony','sector 9')
data['sector'] = data['sector'].str.replace('valley view estate','gwal pahari')

data['sector'] = data['sector'].str.replace('mehrauli  road','sector 14')
data['sector'] = data['sector'].str.replace('jyoti park','sector 7')
data['sector'] = data['sector'].str.replace('ansal plaza','sector 23')
data['sector'] = data['sector'].str.replace('dayanand colony','sector 6')
data['sector'] = data['sector'].str.replace('sushant lok phase 2','sector 55')
data['sector'] = data['sector'].str.replace('chakkarpur','sector 28')
data['sector'] = data['sector'].str.replace('greenwood city','sector 45')
data['sector'] = data['sector'].str.replace('subhash nagar','sector 12')

data['sector'] = data['sector'].str.replace('sohna road road','sohna road')
data['sector'] = data['sector'].str.replace('malibu town','sector 47')
data['sector'] = data['sector'].str.replace('surat nagar 1','sector 104')
data['sector'] = data['sector'].str.replace('new colony','sector 7')
data['sector'] = data['sector'].str.replace('mianwali colony','sector 12')
data['sector'] = data['sector'].str.replace('jacobpura','sector 12')
data['sector'] = data['sector'].str.replace('rajiv nagar','sector 13')
data['sector'] = data['sector'].str.replace('ashok vihar','sector 3')

data['sector'] = data['sector'].str.replace('dlf phase 1','sector 26')
data['sector'] = data['sector'].str.replace('nirvana country','sector 50')
data['sector'] = data['sector'].str.replace('palam vihar','sector 2')
data['sector'] = data['sector'].str.replace('dlf phase 2','sector 25')
data['sector'] = data['sector'].str.replace('sushant lok phase 1','sector 43')
data['sector'] = data['sector'].str.replace('laxman vihar','sector 4')
data['sector'] = data['sector'].str.replace('dlf phase 4','sector 28')
data['sector'] = data['sector'].str.replace('dlf phase 3','sector 24')

data['sector'] = data['sector'].str.replace('sushant lok phase 3','sector 57')
data['sector'] = data['sector'].str.replace('dlf phase 5','sector 43')
data['sector'] = data['sector'].str.replace('rajendra park','sector 105')
data['sector'] = data['sector'].str.replace('uppals southend','sector 49')
data['sector'] = data['sector'].str.replace('sohna','sohna road')
data['sector'] = data['sector'].str.replace('ashok vihar phase 3 extension','sector 5')
data['sector'] = data['sector'].str.replace('south city 1','sector 41')
data['sector'] = data['sector'].str.replace('ashok vihar phase 2','sector 5')

In [31]:
a = data['sector'].value_counts()[data['sector'].value_counts() >= 3]
data = data[data['sector'].isin(a.index)]

In [32]:
data['sector'] = data['sector'].str.replace('sector-33 sohna road', 'sector 33')
data['sector'] = data['sector'].str.replace('sector 1 manesar', 'manesar')
data['sector'] = data['sector'].str.replace('sector 4 phase 2', 'sector 4')
data['sector'] = data['sector'].str.replace('sector 1a manesar', 'manesar')
data['sector'] = data['sector'].str.replace('c block sector 43', 'sector 43')
data['sector'] = data['sector'].str.replace('sector 89 a', 'sector 89')
data['sector'] = data['sector'].str.replace('sector 2 extension', 'sector 2')
data['sector'] = data['sector'].str.replace('sector 36 sohna road', 'sector 36')

data['sector'] = data['sector'].str.replace('sector 95a', 'sector 95')
data['sector'] = data['sector'].str.replace('sector 23a', 'sector 23')
data['sector'] = data['sector'].str.replace('sector 12a', 'sector 12')
data['sector'] = data['sector'].str.replace('sector 3a', 'sector 3')
data['sector'] = data['sector'].str.replace('sector 110 a', 'sector 110')
data['sector'] = data['sector'].str.replace('patel nagar', 'sector 15')
data['sector'] = data['sector'].str.replace('a block sector 43', 'sector 43')
data['sector'] = data['sector'].str.replace('maruti kunj', 'sector 12')
data['sector'] = data['sector'].str.replace('b block sector 43', 'sector 43')

In [33]:
data[data['sector'] == 'new']

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
42,4 BHK Flat in New Gurgaon,flat,dlf 76,new,4.00,11428.0,3500.0,Carpet area: 3500 (325.16 sq.m.),4,4,2,"study room,servant room","New Gurgaon, Gurgaon, Haryana",4.0,NaN,Jun 2027,"['Shri Balaji Hospital and Trauma Center', 'S....",This lovely 4 bhk apartment/flat in new gurgao...,"['6 Wardrobe', '1 Fridge', '8 Fan', '1 Exhaust...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...",NaN
1439,2 BHK Flat in New Gurgaon,flat,green court,new,0.38,5507.0,690.0,Carpet area: 690 (64.1 sq.m.),2,2,1,na,"New Gurgaon, Gurgaon, Haryana",7.0,NaN,Under Construction,"['Ing bank ATM', 'Dcb bank ATM', 'Indus ind ba...",We are the proud owners of this 2 bhk apartmen...,[],"['Intercom Facility', 'Lift(s)', 'Maintenance ...",NaN
2515,4 BHK Flat in New Gurgaon,flat,sare homes,new,0.85,4786.0,1776.0,Super Built up area 1776(165 sq.m.),4,4,3,na,"New Gurgaon, Gurgaon, Haryana",3.0,NaN,5 to 10 Year Old,"['Columbia Asia Hospital', 'Apex Multi Special...",Located in the popular residential address of ...,[],NaN,NaN
3119,2 BHK Flat in New Gurgaon,flat,takshila heights sector 37 c,new,0.67,5583.0,1200.0,Super Built up area 1200(111.48 sq.m.),2,2,2,na,"New Gurgaon, Gurgaon, Haryana",3.0,NaN,1 to 5 Year Old,"['Shri Balaji Hospital and Trauma Center', 'S....",Check out this 2 bhk apartment for sale in tak...,[],"['Lift(s)', 'Swimming Pool', 'Visitor Parking'...",NaN

In [34]:
data.loc[42, 'sector'] = 'sector 37'
data.loc[1439, 'sector'] = 'sector 92'
data.loc[2515, 'sector'] = 'sector 90'
data.loc[3119, 'sector'] = 'sector 76'

In [35]:
data[data['sector'] == 'new sector 2']

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
229,2 BHK Flat in New Palam Vihar,flat,my home,new sector 2,0.28,3166.0,884.0,Carpet area: 900 (83.61 sq.m.),2,1,1,others,"F 150/b, New Palam Vihar, Gurgaon, Haryana",2.0,NaN,1 to 5 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...","2 bhk room with wooden coverd ,1 drawing room,...","['3 Wardrobe', '5 Light', '1 Chimney', '1 Modu...","['Water Storage', 'Park']","['Environment4 out of 5', 'Safety4 out of 5', ..."
352,3 Bedroom House for sale in New Palam Vihar,house,independent,new sector 2,1.00,8796.0,1137.0,Plot area 120(100.34 sq.m.)Built Up area: 120 ...,3,2,2,pooja room,"Q-148, New Palam Vihar, Phase-2, Near Royal Oa...",1.0,North,10+ Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...","Ground and first floor, Ground floor: Ground f...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
1015,2 BHK Flat in New Palam Vihar,flat,ompee k s residency,new sector 2,1.60,26936.0,594.0,Carpet area: 66 (55.18 sq.m.),2,2,2,na,"New Palam Vihar, Gurgaon, Haryana",1.0,NaN,1 to 5 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",We are the proud owners of this 2 bhk apartmen...,NaN,NaN,"['Environment4 out of 5', 'Safety4 out of 5', ..."
3843,2 BHK Flat in New Palam Vihar,flat,my home,new sector 2,0.22,4400.0,500.0,Carpet area: 500 (46.45 sq.m.),2,2,1,na,"New Palam Vihar, Gurgaon, Haryana",1.0,NaN,0 to 1 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",Cctv surveillance are provided here. There is ...,"['3 Fan', '1 Exhaust Fan', '15 Light', '1 Modu...",NaN,"['Safety4 out of 5', 'Lifestyle4 out of 5', 'E..."
3885,2 Bedroom House for sale in New Palam Vihar,house,my home,new sector 2,0.34,12592.0,270.0,Plot area 270(25.08 sq.m.),2,2,2,not available,"Ez-19 A, New Palam Vihar, Gurgaon, Haryana",3.0,West,5 to 10 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",There are availability of various facilities l...,"['1 Wardrobe', '3 Fan', '6 Light', 'No AC', 'N...","['Water Storage', 'Park', 'Visitor Parking']","['Environment4 out of 5', 'Lifestyle4 out of 5..."

In [36]:

data.loc[[229,352,1015,3843,3885],'sector'] = 'sector 110'

In [37]:
data.shape

(3803, 21)

In [38]:
data.duplicated().sum()

np.int64(0)

In [39]:
data.head()

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,3 BHK Flat in Sector 76 Gurgaon,flat,whiteland blissville,sector 76,1.92,11794.0,1628.0,Built Up area: 1628 (151.25 sq.m.),3,3,2,na,"Sector 76, Delhi Gurgaon Expressway, Sector 76...",3.0,NaN,undefined,"['Huda Metro Station', 'Vatika City Centre', '...",Best in class property available at sector 76 ...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,NaN
1,3 BHK Flat in Sector 54 Gurgaon,flat,dlf park place,sector 54,4.85,30180.0,1607.0,Super Built up area 1983(184.23 sq.m.)Built Up...,3,4,3+,servant room,"H 6, Sector 54 Gurgaon, Gurgaon, Haryana",6.0,North,5 to 10 Year Old,"['Sector 53-54 Metro Station', 'Sector 54 Chow...",Dlf park place is one of gurgaon's most sought...,"['1 Water Purifier', '9 Fan', '1 Fridge', '4 G...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area5 out of 5', 'Construction5 out of..."
2,3 BHK Flat in Sector 37D Gurgaon,flat,signature global city 37d ph 2,sector 37d,1.35,9375.0,1440.0,Carpet area: 1440 (133.78 sq.m.),3,3,3+,pooja room,"Sector 37D Gurgaon, Gurgaon, Haryana",3.0,NaN,Mar 2024,"['Dwarka Expressway', 'Pataudi Road', 'Euro In...",The property has terrace with the same. Beauti...,[],"['Power Back-up', 'Lift(s)', 'Swimming Pool', ...","['Environment4 out of 5', 'Lifestyle4 out of 5..."
3,2 BHK Flat in Sector 95 Gurgaon,flat,sidhartha ncr one,sector 95,0.55,5556.0,990.0,Built Up area: 990 (91.97 sq.m.)Carpet area: 9...,2,2,3,na,"Sector 95,gurgaon, Sector 95 Gurgaon, Gurgaon,...",15.0,North-East,undefined,NaN,"2 bath, semi-Furnished, 15th floor (Of 20), ov...","['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,"['Environment4 out of 5', 'Safety4.5 out of 5'..."
4,2 BHK Flat in Sector 91 Gurgaon,flat,tarc maceo,sector 91,0.96,5413.0,1774.0,Super Built up area 1404(130.44 sq.m.),2,2,3+,na,"Sector 91 Gurgaon, Gurgaon, Haryana",8.0,East,5 to 10 Year Old,"['Manish Gallexie 91', 'Dwarka Expressway', 'R...",I want to sell my 2 bhk apartment. Its semi fu...,"['2 Wardrobe', '4 Fan', '2 Geyser', '11 Light'...","['Security / Fire Alarm', 'Intercom Facility',...","['Green Area5 out of 5', 'Construction4 out of..."

In [40]:
# features to drop -> property_name, address, description, rating
data.drop(columns=['property_name', 'address', 'description', 'rating'],inplace=True)

In [41]:
data.sample(5)

,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,floorNum,facing,agePossession,nearbyLocations,furnishDetails,features
2607,flat,shapoorji pallonji joyville gurugram,sector 102,1.90,10259.0,1852.0,Super Built up area 1852(172.06 sq.m.)Built Up...,3,3,3+,pooja room,15.0,North-East,0 to 1 Year Old,"['Khan Market', 'The Esplanade Mall', 'Dwarka ...","['4 Fan', '2 Geyser', '6 Light', '5 AC', 'No B...","['Centrally Air Conditioned', 'Water purifier'..."
1824,flat,bestech park view ananda,sector 81,0.90,6618.0,1360.0,Super Built up area 1360(126.35 sq.m.),2,2,3,others,8.0,NaN,0 to 1 Year Old,"['Orris Community Center', 'Petrol Pump', 'Pet...",[],"['Intercom Facility', 'Lift(s)', 'Swimming Poo..."
1666,flat,smart world orchard,sector 61,1.60,13913.0,1150.0,Carpet area: 1150 (106.84 sq.m.),2,2,2,na,4.0,NaN,Under Construction,"['Sector 55-56 Metro station', 'Bestech Centra...",[],"['Lift(s)', 'Swimming Pool', 'Fitness Centre /..."
1572,flat,the roselia 2,sector 95,0.45,6475.0,695.0,Built Up area: 695 (64.57 sq.m.)Carpet area: 5...,2,2,2,na,19.0,North,undefined,NaN,NaN,NaN
2685,flat,experion the heartsong,sector 108,0.98,13343.0,734.0,Super Built up area 1283(119.19 sq.m.)Built Up...,2,3,3,study room,4.0,East,1 to 5 Year Old,"['Galleria 108 Mall', 'Dwarka Expressway', 'Ce...","['1 Bed', '1 Sofa', '8 Light', '3 AC', '1 Curt...","['Security / Fire Alarm', 'Feng Shui / Vaastu ..."

In [ ]:
# feature engineering required -> areaWithType, additionalRoom, facing, 
# agePossession, furnishDetails, features

In [42]:
data.duplicated().sum()

np.int64(122)

In [43]:
data.to_csv('../Dataset/gurgaon_properties_cleaned_v1.csv',index=False)