In [202]:
import pandas as pd
import numpy as np

In [203]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [204]:
data = pd.read_csv("../Dataset/flats.csv")
data.head()

,property_name,link,society,price,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_id
0,2 BHK Flat in Krishna Colony,https://www.99acres.com/2-bhk-bedroom-apartmen...,maa bhagwati residency,45 Lac,"₹ 5,000/sq.ft.",Carpet area: 900 (83.61 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ...",C68850746
1,2 BHK Flat in Ashok Vihar,https://www.99acres.com/2-bhk-bedroom-apartmen...,Apna Enclave,50 Lac,"₹ 7,692/sq.ft.",Carpet area: 650 (60.39 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ...",H68850564
2,2 BHK Flat in Sohna,https://www.99acres.com/2-bhk-bedroom-apartmen...,Tulsiani Easy in Homes,40 Lac,"₹ 6,722/sq.ft.",Carpet area: 595 (55.28 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ...",J68850120
3,2 BHK Flat in Sector 61 Gurgaon,https://www.99acres.com/2-bhk-bedroom-apartmen...,Smart World Orchard,1.47 Crore,"₹ 12,250/sq.ft.",Carpet area: 1200 (111.48 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN,S68849476
4,2 BHK Flat in Sector 92 Gurgaon,https://www.99acres.com/2-bhk-bedroom-apartmen...,Parkwood Westend,70 Lac,"₹ 5,204/sq.ft.",Super Built up area 1345(124.95 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ...",L47956793

In [205]:
# shape
data.shape

(3017, 20)

In [206]:
# info
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 3017 entries, 0 to 3016
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    3017 non-null   str
 1   link             3017 non-null   str
 2   society          3016 non-null   str
 3   price            3007 non-null   str
 4   area             3004 non-null   str
 5   areaWithType     3008 non-null   str
 6   bedRoom          3008 non-null   str
 7   bathroom         3008 non-null   str
 8   balcony          3008 non-null   str
 9   additionalRoom   1694 non-null   str
 10  address          3002 non-null   str
 11  floorNum         3006 non-null   str
 12  facing           2127 non-null   str
 13  agePossession    3007 non-null   str
 14  nearbyLocations  2913 non-null   str
 15  description      3008 non-null   str
 16  furnishDetails   2203 non-null   str
 17  features         2594 non-null   str
 18  rating           2676 non-null   str
 19  property_id      3008 non-null   str
dtypes: str(20)
memory usage: 471.5 KB

In [207]:
# check for duplicates
data.duplicated().sum()

np.int64(0)

In [208]:
# check for missing values
data.isnull().sum()

property_name         0
link                  0
society               1
price                10
area                 13
areaWithType          9
bedRoom               9
bathroom              9
balcony               9
additionalRoom     1323
address              15
floorNum             11
facing              890
agePossession        10
nearbyLocations     104
description           9
furnishDetails      814
features            423
rating              341
property_id           9
dtype: int64

In [209]:
# Columns to drop -> link, property_id

data.drop(columns=['link', 'property_id'], inplace=True)
data.head()

,property_name,society,price,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,45 Lac,"₹ 5,000/sq.ft.",Carpet area: 900 (83.61 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,Apna Enclave,50 Lac,"₹ 7,692/sq.ft.",Carpet area: 650 (60.39 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,Tulsiani Easy in Homes,40 Lac,"₹ 6,722/sq.ft.",Carpet area: 595 (55.28 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,Smart World Orchard,1.47 Crore,"₹ 12,250/sq.ft.",Carpet area: 1200 (111.48 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,Parkwood Westend,70 Lac,"₹ 5,204/sq.ft.",Super Built up area 1345(124.95 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [210]:
# rename columns
data.rename(columns={'area': 'price_per_sqft'}, inplace=True)

In [211]:
# Society
data['society'].value_counts()

society
SS The Leaf3.8 ★                                     73
Tulip Violet4.3 ★                                    40
Shapoorji Pallonji Joyville Gurugram4.0 ★            39
Signature Global Park4.0 ★                           36
Shree Vardhman Victoria3.8 ★                         35
Tulip Violet4.2 ★                                    33
Smart World Orchard                                  32
Smart World Gems                                     32
Emaar MGF Emerald Floors Premier3.8 ★                32
Paras Dews                                           31
DLF The Ultima4.0 ★                                  31
DLF Regal Gardens3.9 ★                               30
Shree Vardhman Flora3.8 ★                            29
M3M Woodshire4.0 ★                                   29
La Vida by Tata Housing                              28
Signature Global Solera3.7 ★                         28
Godrej Nature Plus                                   27
BPTP Terra3.8 ★                                      25
Emaar Gurgaon Greens4.1 ★                            25
DLF New Town Heights 13.9 ★                          24
Eldeco Accolade3.8 ★                                 24
Experion The Heartsong3.9 ★                          24
Vatika Gurgaon 213.7 ★                               24
Bestech Park View Residency3.9 ★                     23
ATS Triumph3.9 ★                                     22
M3M Heights                                          22
Tata Primanti4.1 ★                                   22
Emaar Palm Gardens4.1 ★                              22
ROF Ananda                                           21
Sare Crescent Parc3.5 ★                              21
Godrej 1014.0 ★                                      20
Experion Windchants3.8 ★                             20
Sare Homes                                           19
Antriksh Heights3.7 ★                                19
Supertech Araville                                   18
Sobha City                                           18
CHD Avenue 713.6 ★                                   18
Ambience Creacions                                   18
Indiabulls Centrum Park3.7 ★                         18
ATS Tourmaline3.9 ★                                  18
Mapsko Mount Ville4.1 ★                              18
M3M Golfestate4.4 ★                                  17
GLS Arawali Homes3.8 ★                               17
Pareena Coban Residences                             17
M3M Skywalk                                          17
Conscient Heritage Max4.3 ★                          17
Godrej Summit3.7 ★                                   17
HCBS Sports Ville3.6 ★                               16
M3M Merlin3.7 ★                                      16
Bestech Park View Grand Spa4.3 ★                     16
Godrej Oasis3.9 ★                                    15
Ansal Heights 86                                     15
Umang Monsoon Breeze                                 15
Emaar MGF The Palm Drive4.1 ★                        15
DLF The Primus3.9 ★                                  14
Umang Winter Hills3.9 ★                              14
Ramsons Kshitij3.7 ★                                 14
MVN Athens3.7 ★                                      14
Indiabulls Enigma                                    14
Ireo Victory Valley4.1 ★                             14
The Close North4.0 ★                                 14
Orchid Petals4.1 ★                                   14
Ireo Skyon4.0 ★                                      14
Vatika The Seven Lamps3.8 ★                          14
Imperia The Esfera                                   14
Corona Optus3.9 ★                                    14
Central Park Flower Valley                           13
Bestech Park View Ananda4.2 ★                        13
Puri Emerald Bay3.7 ★                                13
Ireo The Corridors                                   13
Breez Global Hill View                               11
M3M Soulitude                                        11
Godrej Aria3.8 ★                                     11
Raheja Vedaanta3.6 ★                                 11
Adani M2K Oyster Grande3.9 ★                         11
TARC Maceo3.8 ★                                      11
SBTL Caladium                                        11
Alpha Corp GurgaonOne 844.0 ★                        11
DLF The Skycourt4.2 ★                                11
Godrej Air                                           10
Pivotal Devaan                                       10
Breez Global Heights4.2 ★                            10
Emaar MGF Palm Hills4.0 ★                            10
Pyramid Urban Homes 2                                10
Zara Aavaas                                          10
Ramprastha The Edge Towers3.5 ★                      10
DLF New Town Heights 24.0 ★                          10
ATS Kocoon                                           10
Puri Diplomatic Greens4.0 ★                          10
Capital Residences 360                               10
Signature Global Synera3.4 ★                         10
ILD Greens4.1 ★                                       9
Pareena Mi Casa                                       9
Parsvnath Green Ville3.9 ★                            9
Bestech Park View Sanskruti4.2 ★                      9
AIPL The Peaceful Homes3.9 ★                          9
Vatika City4.1 ★                                      9
Microtek Greenburg3.8 ★                               9
Bestech Altura                                        8
M3M Skycity                                           8
GLS Avenue 51                                         8
Assotech Blith                                        8
M3M Capital                                           8
Emaar Digihomes                                       8
Orris Aster Court Premier                             8
The Lions CGHS                                        8
Tulip Ivory3.5 ★                                      8
Vatika Lifestyle Homes3.8 ★                           8
ss                                                    8
AVL 36 Gurgaon3.7 ★                                   8
Birla Navya                                           8
Emaar Imperial Gardens3.8 ★                           7
Mapsko Casa Bella3.8 ★                                7
Sare Crescent Parc Royal Greens Phase 1               7
Signature Global City                                 7
Ansal Housing Highland Park                           7
Trisara Our Homes 3                                   7
AIPL Zen Residences                                   7
Orris Carnation Residency3.7 ★                        7
Sare Green ParC Phase 3                               7
Ireo The Grand Arch4.0 ★                              7
Signature Andour Heights3.8 ★                         7
Signature Global Orchard Avenue3.6 ★                  7
Vipul Lavanya3.9 ★                                    7
Supertech Hues                                        6
Ashiana Mulberry                                      6
DLF Regency Park 13.6 ★                               6
Signature Global City 63A                             6
Signature The Roselia3.6 ★                            6
Greenopolis                                           6
Hero Homes                                            6
Suncity Vatsal Valley                                 6
Sidhartha NCR One Phase 14.2 ★                        6
Signature Global Park 4                               6
HSIIDC Sidco Aravali                                  6
Bestech Park View City4.1 ★                           6
Mapsko Royale Ville3.7 ★                              6
Kiran Residency                                       6
Bestech Park View Spa Next4.0 ★                       6
Parsvnath Exotica3.7 ★                                6
Pyramid Urban                                         6
M3M Sierra 68                                         6
Pioneer Araya3.8 ★                                    6
BPTP Astaire Gardens3.7 ★                             6
Shapoorji Pallonji Joyville Gurugram                  6
Apna Enclave                                          5
Signature Global City 81                              5
Godrej Habitat                                        5
Silverglades The Melia                                5
Pareena Laxmi Apartments3.6 ★                         5
Satya The Hermitage3.5 ★                              5
Central Park Flower Valley Aqua Front Towers          5
Green Court3.7 ★                                      5
Ashiana Anmol3.5 ★                                    5
Signature Global the Millennia                        5
Tulip Monsella                                        5
M3M The Marina4.0 ★                                   5
Central Park Resorts4.4 ★                             5
DLF Regency Park 24.0 ★                               5
Signature Global City 92                              5
Pioneer Park3.8 ★                                     5
Emaar MGF Emerald Estate3.8 ★                         5
Vatika City Homes3.9 ★                                5
DLF Park Place4.1 ★                                   5
Ireo Uptown4.1 ★                                      5
Signature Global Grand IVA3.9 ★                       5
Adani Brahma Samsara Vilasa                           5
Signature Global City 37D Ph 2                        5
ATS Marigold                                          5
Conscient Elevate                                     5
Krisumi Waterfall Residences                          5
Essel Towers                                          5
Vatika Sovereign Park                                 5
Ramprastha Skyz                                       4
Signature The Serenas                                 4
DLF New Town Heights3.7 ★                             4
Lotus Homz4.0 ★                                       4
Unitech Vistas                                        4
ILD Grand                                             4
Global Hill View                                      4
Railway Officers RPF Society                          4
Raheja Navodaya3.6 ★                                  4
DLF The Skycourt                                      4
SS The Coralwood3.4 ★                                 4
Emaar Palm Heights                                    4
Krrish Provence Estate                                4
Orris Aster Court                                     4
Godrej Icon                                           4
Unitech Fresco3.8 ★                                   4
Prime Habitat                                         4
Tata Gurgaon Gateway3.8 ★                             4
HSIIDC Sidco Shivalik Apartments3.8 ★                 4
Godrej Frontier3.7 ★                                  4
Ramprastha Primera                                    4
Sare Petioles                                         4
Corona Gracieux                                       4
Vatika Xpressions                                     3
Raheja Revanta                                        3
Adani Aangan Arcade                                   3
Sare Green Parc                                       3
Chintels Paradiso3.9 ★                                3
Maxworth City Residences                              3
Deepak Minda                                          3
Unitech The Residences3.7 ★                           3
Sidhartha NCR One                                     3
Raheja Sampada                                        3
Bestech Park View City 23.9 ★                         3
AFNHB Jalvayu Vihar3.7 ★                              3
Pyramid Elite                                         3
Brisk Lumbini Terrace Homes                           3
My Home                                               3
Essel Tower                                           3
Krrish Florence Estate                                3
Piedmont Taksila heights3.6 ★                         3
Tulip White3.5 ★                                      3
Sapphire Eighty Three                                 3
DLF The Grove                                         3
Sukhshanti Apartment                                  3
SS Almeria                                            3
DLF Carlton Estate4.0 ★                               3
DLF Belvedere Towers3.8 ★                             3
AIPL Club Residences                                  3
Unitech Heritage City                                 3
Paras Quartier                                        3
Ambience Lagoon3.9 ★                                  3
Unitech Uniworld Gardens3.8 ★                         3
Raheja Atharva3.6 ★                                   3
Tulip Purple                                          3
Vatika Independent Floors3.8 ★                        3
Shree Arihant Apartment                               3
Mahindra Aura4.2 ★                                    3
Shri Banke Bihari Society3.8 ★                        3
Puri Diplomatic Greens3.9 ★                           3
Sunischit Apartments                                  3
Dhoot Time Residency4.0 ★                             3
ATS Kocoon4.2 ★                                       3
Spaze Privy3.9 ★                                      3
Tulip Lemon3.9 ★                                      3
Conscient Habitat3.6 ★                                3
Suncity Platinum Towers                               3
Spaze Privy AT43.9 ★                                  3
Apex Our Homes                                        3
Guru Gram Haryana CGHS4.1 ★                           3
Siddhartha Apartment                                  3
Kendriya Vihar4.1 ★                                   3
Whiteland Blissville                                  3
Signature Global Solera 2                             3
Pivotal Riddhi Siddhi                                 3
Unitech Sunbreeze                                     3
DLF The Arbour                                        3
Sare Green Parc 2                                     3
DLF Express Greens3.9 ★                               3
Spaze Privvy The Address3.9 ★                         3
Shri Ram Apartments                                   3
Tulip Petals3.6 ★                                     3
Sidhartha NCR Greens4.3 ★                             3
Valley View Estate                                    3
The Roselia 2                                         3
Satya Element One                                     3
DLF Royalton Tower                                    3
Smriti Apartment                                      3
Tulsiani Easy in Homes                                2
BPTP Freedom Park Life4.0 ★                           2
Puri The Aravallis                                    2
Ramprastha City                                       2
Ardee City3.8 ★                                       2
Supertech Hilltown                                    2
Raheja Vanya                                          2
Vatika INXT Floors                                    2
Palam Vihar Society                                   2
M3M Urbana                                            2
Ansal Heights3.2 ★                                    2
Suncity Heights3.7 ★                                  2
Ramprastha The Atrium3.4 ★                            2
Today Callidora                                       2
Park Royal Apartment                                  2
Mapsko Paradise3.9 ★                                  2
MRG World Ultimus                                     2
BPTP Pedestal                                         2
Unitech Uniworld Gardens 23.4 ★                       2
Maruti Vihar                                          2
Vasant Appartments                                    2
Landmark The Residency                                2
Mahindra Luminare4.0 ★                                2
The Close South3.9 ★                                  2
lagoon apartment                                      2
Elan The Presidential                                 2
Pioneer Urban Presidia                                2
M3M Latitude                                          2
Ansal API Celebrity Suites                            2
CGHS Airport Apartment                                2
Bestech Spa Signature                                 2
Green Campus CHS                                      2
DLF The Crest3.6 ★                                    2
DLF The Icon3.7 ★                                     2
Professors Enclave CGHS                               2
BPTP Mansions Park Prime                              2
Paras Irene3.7 ★                                      2
DLF The Belaire3.9 ★                                  2
Suncity Avenue 1023.9 ★                               2
BPTP Amstoria3.8 ★                                    2
Emaar MGF The Enclave                                 2
Vipul Belmonte3.9 ★                                   2
Bestech Park View Sanskruti4.1 ★                      2
M3M Ikonic                                            2
The Penthouses at the Hibiscus                        2
SS Hibiscus                                           2
Viridian The Plaza 106                                2
Tulip Leaf                                            2
Tulip Violet                                          2
Vatika Emilia Floors3.7 ★                             2
Emaar MGF Palm Studios                                2
Orchid Island4.2 ★                                    2
Signature Global The Millennia 3                      2
M3M Sky Lofts                                         2
ROF Aalayas3.8 ★                                      2
AWHO Shanti Vihar4.0 ★                                2
Ansal API Esencia3.7 ★                                2
Raheja Atlantis3.8 ★                                  2
Central Park 2 Bellevue                               2
Tulip Orange3.9 ★                                     2
Adani Aangan Galleria                                 2
HCBS Sports Ville                                     2
Housing Board Colony                                  2
Sahara Grace                                          2
Aqua Front Towers                                     2
Oriental Valley CHS                                   2
NBCC Heights3.9 ★                                     2
Supertech Hill Town                                   2
Suncity Avenue 76                                     2
Godrej Nature Plus Serenity                           2
Ashiana Anmol                                         2
Ganga Apartment                                       2
Suposhaa Smartworld Orchard                           2
Mittal Surya Vihar                                    2
Residency Grand                                       2
Samaspurkunj                                          2
om appartments                                        2
Lavanya Apartments                                    2
Apartment                                             2
Vipul World Floors                                    2
Milan CGHS 9                                          2
Element One Service                                   2
Breeze Global Heights                                 2
Shapoorji Pallonji Joyville                           2
Dlf City                                              2
Silverglades Hightown Residences                      2
Surendra Avenue 69                                    2
Ambience Caitriona                                    2
Bhagwati Sadan                                        2
Sidhivinayak Apartments                               2
Jammu and Kashmir Bank Employees CGHS3.7 ★            2
maa bhagwati residency                                1
Parkwood Westend                                      1
Signature Global Infinity Mall                        1
The Cocoon                                            1
Godrej                                                1

In [212]:
data['society'].nunique()

638

In [213]:
# removing the rating from society col. and converting into lowercase 
import re
data['society'] = data['society'].apply(lambda name: re.sub(r'\d+(\.\d+)?\s?★', '', str(name)).strip()).str.lower()
data['society'].value_counts()

society
tulip violet                                     75
ss the leaf                                      74
shapoorji pallonji joyville gurugram             45
dlf new town heights                             38
signature global park                            36
shree vardhman victoria                          35
smart world orchard                              32
smart world gems                                 32
emaar mgf emerald floors premier                 32
paras dews                                       31
dlf the ultima                                   31
dlf regal gardens                                30
m3m woodshire                                    30
shree vardhman flora                             29
la vida by tata housing                          28
signature global solera                          28
godrej nature plus                               27
bptp terra                                       25
emaar gurgaon greens                             25
eldeco accolade                                  24
experion the heartsong                           24
vatika gurgaon                                   24
bestech park view residency                      23
ats triumph                                      22
m3m heights                                      22
tata primanti                                    22
emaar palm gardens                               22
godrej                                           21
rof ananda                                       21
sare crescent parc                               21
experion windchants                              20
sare homes                                       19
antriksh heights                                 19
hcbs sports ville                                18
supertech araville                               18
sobha city                                       18
m3m golfestate                                   18
chd avenue                                       18
ambience creacions                               18
indiabulls centrum park                          18
ats tourmaline                                   18
m3m skywalk                                      18
mapsko mount ville                               18
gls arawali homes                                17
pareena coban residences                         17
conscient heritage max                           17
godrej summit                                    17
m3m merlin                                       16
bestech park view grand spa                      16
ramsons kshitij                                  15
godrej oasis                                     15
ansal heights 86                                 15
umang monsoon breeze                             15
emaar mgf the palm drive                         15
dlf the skycourt                                 15
dlf the primus                                   14
umang winter hills                               14
mvn athens                                       14
indiabulls enigma                                14
ireo victory valley                              14
the close north                                  14
orchid petals                                    14
ireo skyon                                       14
bestech park view ananda                         14
vatika the seven lamps                           14
imperia the esfera                               14
corona optus                                     14
central park flower valley                       13
puri emerald bay                                 13
ats kocoon                                       13
puri diplomatic greens                           13
ireo the corridors                               13
breez global hill view                           11
dlf regency park                                 11
m3m soulitude                                    11
godrej aria                                      11
breez global heights                             11
raheja vedaanta                                  11
adani m2k oyster grande                          11
tarc maceo                                       11
sbtl caladium                                    11
alpha corp gurgaonone                            11
bestech park view sanskruti                      11
ild greens                                       10
godrej air                                       10
pivotal devaan                                   10
emaar mgf palm hills                             10
pyramid urban homes 2                            10
zara aavaas                                      10
ramprastha the edge towers                       10
capital residences 360                           10
signature global synera                          10
bestech park view city                            9
pareena mi casa                                   9
parsvnath green ville                             9
aipl the peaceful homes                           9
vatika city                                       9
microtek greenburg                                9
bestech altura                                    8
m3m skycity                                       8
gls avenue 51                                     8
assotech blith                                    8
m3m capital                                       8
emaar digihomes                                   8
orris aster court premier                         8
the lions cghs                                    8
tulip ivory                                       8
vatika lifestyle homes                            8
ss                                                8
avl 36 gurgaon                                    8
birla navya                                       8
emaar imperial gardens                            7
mapsko casa bella                                 7
sare crescent parc royal greens phase 1           7
signature global city                             7
ansal housing highland park                       7
trisara our homes 3                               7
ashiana anmol                                     7
aipl zen residences                               7
sidhartha ncr one phase                           7
orris carnation residency                         7
sare green parc phase 3                           7
ireo the grand arch                               7
signature andour heights                          7
signature global orchard avenue                   7
vipul lavanya                                     7
supertech hues                                    6
ashiana mulberry                                  6
signature global city 63a                         6
signature the roselia                             6
greenopolis                                       6
hero homes                                        6
green court                                       6
suncity vatsal valley                             6
signature global park 4                           6
hsiidc sidco aravali                              6
mapsko royale ville                               6
kiran residency                                   6
bestech park view spa next                        6
parsvnath exotica                                 6
pyramid urban                                     6
m3m sierra 68                                     6
pioneer araya                                     6
bptp astaire gardens                              6
apna enclave                                      5
signature global city 81                          5
godrej habitat                                    5
silverglades the melia                            5
pareena laxmi apartments                          5
satya the hermitage                               5
central park flower valley aqua front towers      5
signature global the millennia                    5
tulip monsella                                    5
m3m the marina                                    5
unitech uniworld gardens                          5
central park resorts                              5
signature global city 92                          5
pioneer park                                      5
emaar mgf emerald estate                          5
vatika city homes                                 5
unitech fresco                                    5
dlf park place                                    5
ireo uptown                                       5
signature global grand iva                        5
adani brahma samsara vilasa                       5
signature global city 37d ph 2                    5
ats marigold                                      5
conscient elevate                                 5
krisumi waterfall residences                      5
essel towers                                      5
vatika sovereign park                             5
ramprastha skyz                                   4
signature the serenas                             4
afnhb jalvayu vihar                               4
essel tower                                       4
lotus homz                                        4
unitech vistas                                    4
ild grand                                         4
global hill view                                  4
railway officers rpf society                      4
raheja navodaya                                   4
ss the coralwood                                  4
emaar palm heights                                4
krrish provence estate                            4
orris aster court                                 4
godrej icon                                       4
prime habitat                                     4
tata gurgaon gateway                              4
hsiidc sidco shivalik apartments                  4
godrej frontier                                   4
ramprastha primera                                4
kendriya vihar                                    4
dlf the arbour                                    4
sare petioles                                     4
corona gracieux                                   4
vatika xpressions                                 3
raheja revanta                                    3
adani aangan arcade                               3
sare green parc                                   3
chintels paradiso                                 3
maxworth city residences                          3
deepak minda                                      3
unitech the residences                            3
sidhartha ncr one                                 3
raheja sampada                                    3
pyramid elite                                     3
brisk lumbini terrace homes                       3
my home                                           3
bhagwati sadan                                    3
krrish florence estate                            3
piedmont taksila heights                          3
tulip white                                       3
sapphire eighty three                             3
dlf the grove                                     3
sukhshanti apartment                              3
ss almeria                                        3
dlf carlton estate                                3
dlf belvedere towers                              3
aipl club residences                              3
unitech heritage city                             3
paras quartier                                    3
ambience lagoon                                   3
raheja atharva                                    3
tulip purple                                      3
vatika independent floors                         3
shree arihant apartment                           3
mahindra aura                                     3
shri banke bihari society                         3
sunischit apartments                              3
dhoot time residency                              3
spaze privy                                       3
tulip lemon                                       3
conscient habitat                                 3
suncity platinum towers                           3
spaze privy at                                    3
apex our homes                                    3
guru gram haryana cghs                            3
siddhartha apartment                              3
whiteland blissville                              3
signature global solera 2                         3
pivotal riddhi siddhi                             3
unitech sunbreeze                                 3
sare green parc 2                                 3
dlf express greens                                3
spaze privvy the address                          3
shri ram apartments                               3
tulip petals                                      3
sidhartha ncr greens                              3
valley view estate                                3
the roselia 2                                     3
satya element one                                 3
dlf royalton tower                                3
smriti apartment                                  3
tulsiani easy in homes                            2
shree shyam residency                             2
bptp freedom park life                            2
puri the aravallis                                2
ramprastha city                                   2
ardee city                                        2
supertech hilltown                                2
raheja vanya                                      2
vatika inxt floors                                2
palam vihar society                               2
m3m urbana                                        2
ansal heights                                     2
suncity heights                                   2
ramprastha the atrium                             2
today callidora                                   2
park royal apartment                              2
mapsko paradise                                   2
mrg world ultimus                                 2
bptp pedestal                                     2
maruti vihar                                      2
vasant appartments                                2
landmark the residency                            2
mahindra luminare                                 2
the close south                                   2
lagoon apartment                                  2
elan the presidential                             2
pioneer urban presidia                            2
m3m latitude                                      2
ansal api celebrity suites                        2
cghs airport apartment                            2
bestech spa signature                             2
green campus chs                                  2
dlf the crest                                     2
dlf the icon                                      2
professors enclave cghs                           2
bptp mansions park prime                          2
paras irene                                       2
dlf the belaire                                   2
suncity avenue                                    2
bptp amstoria                                     2
emaar mgf the enclave                             2
vipul belmonte                                    2
m3m ikonic                                        2
the penthouses at the hibiscus                    2
ss hibiscus                                       2
viridian the plaza 106                            2
tulip leaf                                        2
vatika emilia floors                              2
emaar mgf palm studios                            2
orchid island                                     2
signature global the millennia 3                  2
m3m sky lofts                                     2
rof aalayas                                       2
awho shanti vihar                                 2
ansal api esencia                                 2
shyam apartment                                   2
raheja atlantis                                   2
central park 2 bellevue                           2
tulip orange                                      2
adani aangan galleria                             2
housing board colony                              2
sahara grace                                      2
aqua front towers                                 2
oriental valley chs                               2
emaar mgf emerald floors                          2
nbcc heights                                      2
supertech hill town                               2
suncity avenue 76                                 2
godrej nature plus serenity                       2
ganga apartment                                   2
suposhaa smartworld orchard                       2
mittal surya vihar                                2
residency grand                                   2
ss residency                                      2
samaspurkunj                                      2
om appartments                                    2
lavanya apartments                                2
apartment                                         2
vipul world floors                                2
milan cghs 9                                      2
element one service                               2
breeze global heights                             2
shapoorji pallonji joyville                       2
dlf city                                          2
silverglades hightown residences                  2
surendra avenue 69                                2
ambience caitriona                                2
sidhivinayak apartments                           2
jammu and kashmir bank employees cghs             2
maa bhagwati residency                            1
parkwood westend                                  1
signature global infinity mall                    1
the cocoon                                        1
senate court                                      1
signature global orchard avenue 2                 1
the new people apartments                         1
the serenas                                       1
central park resort belgravia residences          1
apex builders                                     1
ompee k s residency                               1
bhawna cghs                                       1
ansal sushant lok ci                              1
godrej meridien                                   1
pooja apartment                                   1
gokuldham society, bahadurgarh                    1
4s aradhya homes                                  1
emaar mgf palm terraces                           1
anamika enclave                                   1
huda ashok vihar phase                            1
emaar palm premier                                1
conscient one                                     1
not applicable                                    1
smartworld 1dxp                                   1
czar mahira homes 63a                             1
godrej summit premia towers                       1
m3m one key resiments                             1
sushant lok 1 builder floors                      1
vatika sovereign next sector-82 a gurgaon         1
micasa sec 68                                     1
shyam sadan                                       1
hanumanta apartment                               1
ashiyara 2                                        1
m3m golf hills phase 1                            1
abhinav group housing society                     1
signature signum 95a                              1
aardhya homesh                                    1
sonata group housing society sector 1 manesar     1
experion heartsong                                1
project krishna colony                            1
m3m antalya hills                                 1
malibu towne                                      1

In [214]:
# Prices -> all values are in lac or Crore, 
# except 11 properties have no values instead "Price on Request"

data['price'].value_counts()

price
1.25 Crore          79
1.1 Crore           61
1.4 Crore           60
1.2 Crore           59
1.5 Crore           59
90 Lac              58
1.3 Crore           57
95 Lac              53
2 Crore             51
1.75 Crore          47
1 Crore             46
1.6 Crore           43
1.35 Crore          41
1.55 Crore          40
1.9 Crore           40
75 Lac              38
1.65 Crore          38
1.8 Crore           37
1.7 Crore           37
80 Lac              36
2.2 Crore           34
50 Lac              33
1.15 Crore          33
85 Lac              31
1.45 Crore          31
1.05 Crore          30
40 Lac              29
2.5 Crore           29
60 Lac              29
45 Lac              26
2.1 Crore           26
65 Lac              25
1.85 Crore          23
2.35 Crore          23
35 Lac              23
3 Crore             22
70 Lac              21
2.25 Crore          20
55 Lac              20
3.5 Crore           19
2.4 Crore           18
2.3 Crore           18
30 Lac              17
2.65 Crore          16
1.38 Crore          15
2.6 Crore           15
2.15 Crore          14
3.4 Crore           14
2.45 Crore          14
3.25 Crore          13
82 Lac              13
78 Lac              13
2.7 Crore           13
38 Lac              13
1.32 Crore          13
92 Lac              13
42 Lac              12
2.8 Crore           12
1.95 Crore          12
1.42 Crore          12
5 Crore             12
Price on Request    11
25 Lac              11
32 Lac              11
88 Lac              11
1.08 Crore          11
28 Lac              10
26 Lac              10
87 Lac              10
1.28 Crore          10
2.55 Crore          10
1.78 Crore          10
1.12 Crore          10
2.85 Crore           9
99 Lac               9
22 Lac               9
36 Lac               9
2.05 Crore           9
4 Crore              9
3.45 Crore           9
1.68 Crore           9
1.72 Crore           9
86 Lac               8
3.2 Crore            8
56 Lac               8
2.75 Crore           8
27 Lac               8
4.25 Crore           8
1.18 Crore           8
1.54 Crore           8
6.5 Crore            8
6 Crore              8
1.76 Crore           8
98 Lac               8
1.26 Crore           8
48 Lac               8
20 Lac               8
1.99 Crore           7
79 Lac               7
46 Lac               7
1.29 Crore           7
2.9 Crore            7
39 Lac               7
72 Lac               7
97 Lac               7
3.7 Crore            7
1.27 Crore           7
1.36 Crore           7
3.3 Crore            7
1.19 Crore           7
1.02 Crore           7
96 Lac               6
1.01 Crore           6
43 Lac               6
3.35 Crore           6
54 Lac               6
4.1 Crore            6
71.5 Lac             6
1.49 Crore           6
3.9 Crore            6
1.98 Crore           6
3.65 Crore           6
5.5 Crore            6
1.07 Crore           6
1.51 Crore           6
2.95 Crore           6
3.05 Crore           6
1.16 Crore           6
21 Lac               6
1.59 Crore           6
1.14 Crore           6
1.39 Crore           6
1.34 Crore           6
1.13 Crore           6
37 Lac               6
1.47 Crore           5
29 Lac               5
1.83 Crore           5
93 Lac               5
4.5 Crore            5
64 Lac               5
24 Lac               5
1.79 Crore           5
2.29 Crore           5
66 Lac               5
1.93 Crore           5
2.12 Crore           5
3.75 Crore           5
6.75 Crore           5
1.33 Crore           5
49 Lac               5
2.78 Crore           5
1.24 Crore           5
1.17 Crore           5
2.22 Crore           5
1.82 Crore           5
1.43 Crore           5
1.91 Crore           5
1.69 Crore           5
1.44 Crore           5
1.92 Crore           5
68 Lac               5
1.62 Crore           5
3.95 Crore           4
6.15 Crore           4
74 Lac               4
28.5 Lac             4
1.71 Crore           4
1.48 Crore           4
5.6 Crore            4
5.9 Crore            4
1.64 Crore           4
3.6 Crore            4
1.77 Crore           4
1.52 Crore           4
62 Lac               4
1.73 Crore           4
5.25 Crore           4
1.37 Crore           4
1.31 Crore           4
1.58 Crore           4
2.09 Crore           4
41.5 Lac             4
1.22 Crore           4
4.3 Crore            4
4.85 Crore           4
7 Crore              4
3.1 Crore            4
1.66 Crore           4
31 Lac               4
89 Lac               4
73 Lac               4
36.5 Lac             4
33 Lac               4
1.23 Crore           4
67 Lac               4
58 Lac               4
4.75 Crore           3
83 Lac               3
34 Lac               3
3.85 Crore           3
2.33 Crore           3
2.79 Crore           3
1.41 Crore           3
91 Lac               3
3.49 Crore           3
1.67 Crore           3
4.8 Crore            3
2.51 Crore           3
2.01 Crore           3
2.08 Crore           3
69 Lac               3
1.09 Crore           3
2.28 Crore           3
3.8 Crore            3
2.03 Crore           3
1.04 Crore           3
2.24 Crore           3
52 Lac               3
3.15 Crore           3
1.21 Crore           3
2.36 Crore           3
1.57 Crore           3
64.5 Lac             3
1.88 Crore           3
84 Lac               3
51 Lac               3
5.8 Crore            3
1.63 Crore           3
72.5 Lac             3
4.2 Crore            3
94 Lac               3
47 Lac               3
41 Lac               2
31.5 Lac             2
2.91 Crore           2
59 Lac               2
3.29 Crore           2
71 Lac               2
87.5 Lac             2
52.56 Lac            2
5.7 Crore            2
1.56 Crore           2
2.26 Crore           2
2.99 Crore           2
2.87 Crore           2
2.57 Crore           2
5.2 Crore            2
4.6 Crore            2
3.21 Crore           2
3.32 Crore           2
1.87 Crore           2
3.55 Crore           2
98.5 Lac             2
56.2 Lac             2
88.5 Lac             2
4.7 Crore            2
4.45 Crore           2
27.75 Lac            2
2.04 Crore           2
4.55 Crore           2
7.5 Crore            2
11 Crore             2
27.1 Lac             2
2.58 Crore           2
2.14 Crore           2
53 Lac               2
77.5 Lac             2
6.2 Crore            2
2.23 Crore           2
53.5 Lac             2
4.49 Crore           2
2.52 Crore           2
2.13 Crore           2
2.17 Crore           2
8.5 Crore            2
8 Crore              2
1.46 Crore           2
25.5 Lac             2
4.26 Crore           2
2.41 Crore           2
2.02 Crore           2
14 Crore             2
6.25 Crore           1
29.99 Lac            1
23 Lac               1
31.75 Lac            1
3.87 Crore           1
29.5 Lac             1
3.67 Crore           1
8.25 Crore           1
2.37 Crore           1
4.67 Crore           1
3.39 Crore           1
3.63 Crore           1
2.34 Crore           1
3.79 Crore           1
5.49 Crore           1
6.3 Crore            1
11.25 Crore          1
7.15 Crore           1
2.82 Crore           1
54.99 Lac            1
4.95 Crore           1
5.31 Crore           1
3.19 Crore           1
4.4 Crore            1
4.63 Crore           1
2.98 Crore           1
66.99 Lac            1
4.78 Crore           1
6.16 Crore           1
5.3 Crore            1
2.72 Crore           1
2.21 Crore           1
89.5 Lac             1
2.48 Crore           1
99.5 Lac             1
3.83 Crore           1
95.75 Lac            1
3.46 Crore           1
5.4 Crore            1
55.6 Lac             1
98.1 Lac             1
2.63 Crore           1
55.5 Lac             1
1.11 Crore           1
6.44 Crore           1
7.56 Crore           1
4.79 Crore           1
2.97 Crore           1
94.25 Lac            1
80.5 Lac             1
93.75 Lac            1
85.5 Lac             1
68.5 Lac             1
79.9 Lac             1
71.2 Lac             1
27.5 Lac             1
23.5 Lac             1
35.5 Lac             1
4.94 Crore           1
10.75 Crore          1
9.14 Crore           1
8.35 Crore           1
81 Lac               1
26.1 Lac             1
1.06 Crore           1
2.11 Crore           1
6.1 Crore            1
5.75 Crore           1
10 Crore             1
24.5 Lac             1
17.5 Lac             1
20.5 Lac             1
47.5 Lac             1
2.77 Crore           1
42.5 Lac             1
2.61 Crore           1
65.5 Lac             1
53.2 Lac             1
90.5 Lac             1
52.5 Lac             1
2.62 Crore           1
4.86 Crore           1
5.15 Crore           1
9.3 Crore            1
1.74 Crore           1
4.21 Crore           1
4.16 Crore           1
4.52 Crore           1
1.84 Crore           1
8.44 Crore           1
13.2 Crore           1
2.92 Crore           1
2.38 Crore           1
97.5 Lac             1
2.64 Crore           1
2.49 Crore           1
63.4 Lac             1
2.06 Crore           1
2.07 Crore           1
44 Lac               1
2.32 Crore           1
1.86 Crore           1
85.75 Lac            1
87.99 Lac            1
86.99 Lac            1
9.95 Crore           1
9.2 Crore            1
49.5 Lac             1
16 Lac               1
2.86 Crore           1
86.92 Lac            1
94.99 Lac            1
88.4 Lac             1
3.72 Crore           1
57 Lac               1
95.5 Lac             1
96.07 Lac            1
19 Lac               1
70.85 Lac            1
7.52 Crore           1
40.3 Lac             1
32.5 Lac             1
2.96 Crore           1
1.53 Crore           1
82.5 Lac             1
61 Lac               1
15 Crore             1
7.8 Crore            1
1.97 Crore           1
39.5 Lac             1
4.02 Crore           1
3.98 Crore           1
54.8 Lac             1
2.69 Crore           1
2.54 Crore           1
37.5 Lac             1
97.04 Lac            1
3.23 Crore           1
7.9 Crore            1
6.02 Crore           1
29.8 Lac             1
94.5 Lac             1
2.44 Crore           1
9 Crore              1
3.99 Crore           1
64.45 Lac            1
37.1 Lac             1
7.4 Crore            1
3.78 Crore           1
98.88 Lac            1
68.85 Lac            1
26.9 Lac             1
26.5 Lac             1
73.53 Lac            1
89.77 Lac            1
62.5 Lac             1
Name: count, dtype: int64

In [215]:
# remove rows having "Price per Request"
data = data[data['price'] != "Price on Request"]
data.head()

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,45 Lac,"₹ 5,000/sq.ft.",Carpet area: 900 (83.61 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,apna enclave,50 Lac,"₹ 7,692/sq.ft.",Carpet area: 650 (60.39 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,tulsiani easy in homes,40 Lac,"₹ 6,722/sq.ft.",Carpet area: 595 (55.28 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,smart world orchard,1.47 Crore,"₹ 12,250/sq.ft.",Carpet area: 1200 (111.48 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,parkwood westend,70 Lac,"₹ 5,204/sq.ft.",Super Built up area 1345(124.95 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [216]:
# Converting all the values into crore

def treat_price(x):
    if type(x) == float:
        return x
    else:
        if x[1] == 'Lac':
            return round(float(x[0])/100, 2)
        else:
            return round(float(x[0]), 2)

In [217]:
data['price'] = data['price'].str.split(' ').apply(treat_price)
data.head()

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,"₹ 5,000/sq.ft.",Carpet area: 900 (83.61 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,apna enclave,0.50,"₹ 7,692/sq.ft.",Carpet area: 650 (60.39 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,tulsiani easy in homes,0.40,"₹ 6,722/sq.ft.",Carpet area: 595 (55.28 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,smart world orchard,1.47,"₹ 12,250/sq.ft.",Carpet area: 1200 (111.48 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,parkwood westend,0.70,"₹ 5,204/sq.ft.",Super Built up area 1345(124.95 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [218]:
# price_per_sqft -> consistent data -> all values are in /sq.fit

data['price_per_sqft'].value_counts()

price_per_sqft
₹ 10,000/sq.ft.     19
₹ 8,000/sq.ft.      16
₹ 12,500/sq.ft.     16
₹ 5,000/sq.ft.      13
₹ 6,666/sq.ft.      13
₹ 7,500/sq.ft.      12
₹ 8,333/sq.ft.      12
₹ 6,000/sq.ft.      11
₹ 8,461/sq.ft.       9
₹ 7,000/sq.ft.       8
₹ 12,000/sq.ft.      8
₹ 9,000/sq.ft.       7
₹ 11,111/sq.ft.      6
₹ 6,578/sq.ft.       6
₹ 8,928/sq.ft.       6
₹ 11,500/sq.ft.      6
₹ 5,500/sq.ft.       6
₹ 8,888/sq.ft.       6
₹ 9,230/sq.ft.       6
₹ 7,692/sq.ft.       5
₹ 5,384/sq.ft.       5
₹ 5,600/sq.ft.       5
₹ 16,000/sq.ft.      5
₹ 10,714/sq.ft.      5
₹ 5,556/sq.ft.       5
₹ 6,500/sq.ft.       5
₹ 7,407/sq.ft.       5
₹ 4,615/sq.ft.       5
₹ 4,666/sq.ft.       5
₹ 4,444/sq.ft.       5
₹ 14,242/sq.ft.      5
₹ 7,142/sq.ft.       5
₹ 7,641/sq.ft.       5
₹ 8,571/sq.ft.       5
₹ 8,205/sq.ft.       5
₹ 11,428/sq.ft.      5
₹ 8,432/sq.ft.       4
₹ 4,687/sq.ft.       4
₹ 8,784/sq.ft.       4
₹ 13,750/sq.ft.      4
₹ 4,500/sq.ft.       4
₹ 15,000/sq.ft.      4
₹ 8,043/sq.ft.       4
₹ 8,108/sq.ft.       4
₹ 6,250/sq.ft.       4
₹ 7,496/sq.ft.       4
₹ 7,272/sq.ft.       4
₹ 9,090/sq.ft.       4
₹ 13,636/sq.ft.      4
₹ 15,384/sq.ft.      4
₹ 8,484/sq.ft.       4
₹ 14,418/sq.ft.      4
₹ 8,163/sq.ft.       4
₹ 9,210/sq.ft.       4
₹ 7,812/sq.ft.       4
₹ 8,139/sq.ft.       4
₹ 11,666/sq.ft.      4
₹ 8,474/sq.ft.       4
₹ 4,814/sq.ft.       4
₹ 5,660/sq.ft.       4
₹ 9,822/sq.ft.       4
₹ 16,666/sq.ft.      4
₹ 7,250/sq.ft.       4
₹ 10,416/sq.ft.      4
₹ 7,317/sq.ft.       4
₹ 8,445/sq.ft.       4
₹ 6,735/sq.ft.       4
₹ 8,358/sq.ft.       4
₹ 4,854/sq.ft.       4
₹ 8,787/sq.ft.       4
₹ 8,500/sq.ft.       4
₹ 13,913/sq.ft.      4
₹ 10,383/sq.ft.      4
₹ 8,148/sq.ft.       3
₹ 8,604/sq.ft.       3
₹ 16,969/sq.ft.      3
₹ 5,555/sq.ft.       3
₹ 6,404/sq.ft.       3
₹ 10,500/sq.ft.      3
₹ 5,397/sq.ft.       3
₹ 6,470/sq.ft.       3
₹ 9,615/sq.ft.       3
₹ 6,593/sq.ft.       3
₹ 10,139/sq.ft.      3
₹ 9,904/sq.ft.       3
₹ 4,105/sq.ft.       3
₹ 6,667/sq.ft.       3
₹ 8,450/sq.ft.       3
₹ 8,886/sq.ft.       3
₹ 6,542/sq.ft.       3
₹ 4,820/sq.ft.       3
₹ 4,800/sq.ft.       3
₹ 7,865/sq.ft.       3
₹ 7,400/sq.ft.       3
₹ 13,000/sq.ft.      3
₹ 6,921/sq.ft.       3
₹ 8,620/sq.ft.       3
₹ 8,181/sq.ft.       3
₹ 9,900/sq.ft.       3
₹ 9,473/sq.ft.       3
₹ 8,606/sq.ft.       3
₹ 14,254/sq.ft.      3
₹ 7,541/sq.ft.       3
₹ 8,080/sq.ft.       3
₹ 7,150/sq.ft.       3
₹ 7,586/sq.ft.       3
₹ 7,948/sq.ft.       3
₹ 16,470/sq.ft.      3
₹ 6,476/sq.ft.       3
₹ 7,750/sq.ft.       3
₹ 5,878/sq.ft.       3
₹ 13,392/sq.ft.      3
₹ 8,389/sq.ft.       3
₹ 8,750/sq.ft.       3
₹ 5,856/sq.ft.       3
₹ 7,179/sq.ft.       3
₹ 8,532/sq.ft.       3
₹ 9,011/sq.ft.       3
₹ 7,954/sq.ft.       3
₹ 8,400/sq.ft.       3
₹ 10,638/sq.ft.      3
₹ 9,972/sq.ft.       3
₹ 6,086/sq.ft.       3
₹ 6,421/sq.ft.       3
₹ 11,000/sq.ft.      3
₹ 11,363/sq.ft.      3
₹ 7,302/sq.ft.       3
₹ 14,430/sq.ft.      3
₹ 6,387/sq.ft.       3
₹ 5,833/sq.ft.       3
₹ 8,222/sq.ft.       3
₹ 6,818/sq.ft.       3
₹ 8,078/sq.ft.       3
₹ 8,215/sq.ft.       3
₹ 5,238/sq.ft.       3
₹ 5,735/sq.ft.       3
₹ 10,555/sq.ft.      3
₹ 7,467/sq.ft.       3
₹ 9,500/sq.ft.       3
₹ 14,000/sq.ft.      3
₹ 10,204/sq.ft.      3
₹ 4,513/sq.ft.       3
₹ 4,210/sq.ft.       3
₹ 7,549/sq.ft.       3
₹ 13,870/sq.ft.      3
₹ 7,056/sq.ft.       3
₹ 5,319/sq.ft.       3
₹ 6,644/sq.ft.       3
₹ 7,083/sq.ft.       3
₹ 5,325/sq.ft.       3
₹ 6,722/sq.ft.       2
₹ 12,250/sq.ft.      2
₹ 13,333/sq.ft.      2
₹ 6,859/sq.ft.       2
₹ 10,476/sq.ft.      2
₹ 7,796/sq.ft.       2
₹ 9,135/sq.ft.       2
₹ 6,538/sq.ft.       2
₹ 6,950/sq.ft.       2
₹ 5,714/sq.ft.       2
₹ 15,151/sq.ft.      2
₹ 6,200/sq.ft.       2
₹ 7,846/sq.ft.       2
₹ 7,297/sq.ft.       2
₹ 14,545/sq.ft.      2
₹ 5,424/sq.ft.       2
₹ 7,857/sq.ft.       2
₹ 5,521/sq.ft.       2
₹ 6,812/sq.ft.       2
₹ 5,128/sq.ft.       2
₹ 10,599/sq.ft.      2
₹ 6,338/sq.ft.       2
₹ 8,035/sq.ft.       2
₹ 8,036/sq.ft.       2
₹ 8,611/sq.ft.       2
₹ 5,641/sq.ft.       2
₹ 10,018/sq.ft.      2
₹ 9,027/sq.ft.       2
₹ 6,420/sq.ft.       2
₹ 5,405/sq.ft.       2
₹ 11,755/sq.ft.      2
₹ 9,146/sq.ft.       2
₹ 7,396/sq.ft.       2
₹ 6,111/sq.ft.       2
₹ 7,782/sq.ft.       2
₹ 7,780/sq.ft.       2
₹ 6,789/sq.ft.       2
₹ 6,967/sq.ft.       2
₹ 7,627/sq.ft.       2
₹ 6,506/sq.ft.       2
₹ 8,504/sq.ft.       2
₹ 9,166/sq.ft.       2
₹ 18,000/sq.ft.      2
₹ 11,724/sq.ft.      2
₹ 6,024/sq.ft.       2
₹ 5,882/sq.ft.       2
₹ 13,500/sq.ft.      2
₹ 9,909/sq.ft.       2
₹ 9,876/sq.ft.       2
₹ 7,585/sq.ft.       2
₹ 10,601/sq.ft.      2
₹ 6,983/sq.ft.       2
₹ 6,739/sq.ft.       2
₹ 6,325/sq.ft.       2
₹ 6,061/sq.ft.       2
₹ 6,429/sq.ft.       2
₹ 6,377/sq.ft.       2
₹ 10,531/sq.ft.      2
₹ 5,038/sq.ft.       2
₹ 5,797/sq.ft.       2
₹ 9,286/sq.ft.       2
₹ 6,510/sq.ft.       2
₹ 41,245/sq.ft.      2
₹ 9,851/sq.ft.       2
₹ 8,075/sq.ft.       2
₹ 7,727/sq.ft.       2
₹ 15,998/sq.ft.      2
₹ 14,257/sq.ft.      2
₹ 9,333/sq.ft.       2
₹ 14,214/sq.ft.      2
₹ 7,248/sq.ft.       2
₹ 10,603/sq.ft.      2
₹ 7,391/sq.ft.       2
₹ 16,960/sq.ft.      2
₹ 11,516/sq.ft.      2
₹ 17,619/sq.ft.      2
₹ 8,206/sq.ft.       2
₹ 6,597/sq.ft.       2
₹ 18,181/sq.ft.      2
₹ 4,271/sq.ft.       2
₹ 9,182/sq.ft.       2
₹ 12,782/sq.ft.      2
₹ 8,072/sq.ft.       2
₹ 14,583/sq.ft.      2
₹ 14,478/sq.ft.      2
₹ 4,651/sq.ft.       2
₹ 14,800/sq.ft.      2
₹ 8,521/sq.ft.       2
₹ 11,028/sq.ft.      2
₹ 6,134/sq.ft.       2
₹ 13,281/sq.ft.      2
₹ 7,825/sq.ft.       2
₹ 13,224/sq.ft.      2
₹ 5,681/sq.ft.       2
₹ 7,884/sq.ft.       2
₹ 13,383/sq.ft.      2
₹ 11,505/sq.ft.      2
₹ 8,410/sq.ft.       2
₹ 10,516/sq.ft.      2
₹ 10,936/sq.ft.      2
₹ 7,945/sq.ft.       2
₹ 6,049/sq.ft.       2
₹ 6,679/sq.ft.       2
₹ 6,141/sq.ft.       2
₹ 8,376/sq.ft.       2
₹ 7,610/sq.ft.       2
₹ 7,350/sq.ft.       2
₹ 13,076/sq.ft.      2
₹ 6,987/sq.ft.       2
₹ 11,412/sq.ft.      2
₹ 4,857/sq.ft.       2
₹ 8,632/sq.ft.       2
₹ 5,513/sq.ft.       2
₹ 5,896/sq.ft.       2
₹ 8,834/sq.ft.       2
₹ 6,313/sq.ft.       2
₹ 19,747/sq.ft.      2
₹ 7,878/sq.ft.       2
₹ 9,105/sq.ft.       2
₹ 10,699/sq.ft.      2
₹ 7,608/sq.ft.       2
₹ 6,655/sq.ft.       2
₹ 5,674/sq.ft.       2
₹ 8,947/sq.ft.       2
₹ 5,683/sq.ft.       2
₹ 7,449/sq.ft.       2
₹ 18,518/sq.ft.      2
₹ 12,222/sq.ft.      2
₹ 10,596/sq.ft.      2
₹ 7,014/sq.ft.       2
₹ 5,825/sq.ft.       2
₹ 8,100/sq.ft.       2
₹ 6,455/sq.ft.       2
₹ 5,588/sq.ft.       2
₹ 9,128/sq.ft.       2
₹ 11,574/sq.ft.      2
₹ 7,223/sq.ft.       2
₹ 13,343/sq.ft.      2
₹ 5,820/sq.ft.       2
₹ 6,254/sq.ft.       2
₹ 6,825/sq.ft.       2
₹ 6,647/sq.ft.       2
₹ 9,642/sq.ft.       2
₹ 11,694/sq.ft.      2
₹ 6,029/sq.ft.       2
₹ 10,545/sq.ft.      2
₹ 7,751/sq.ft.       2
₹ 5,725/sq.ft.       2
₹ 9,433/sq.ft.       2
₹ 10,651/sq.ft.      2
₹ 5,808/sq.ft.       2
₹ 4,080/sq.ft.       2
₹ 10,237/sq.ft.      2
₹ 12,444/sq.ft.      2
₹ 6,692/sq.ft.       2
₹ 5,252/sq.ft.       2
₹ 13,928/sq.ft.      2
₹ 7,850/sq.ft.       2
₹ 7,817/sq.ft.       2
₹ 9,565/sq.ft.       2
₹ 15,454/sq.ft.      2
₹ 6,571/sq.ft.       2
₹ 6,774/sq.ft.       2
₹ 9,139/sq.ft.       2
₹ 11,727/sq.ft.      2
₹ 10,489/sq.ft.      2
₹ 15,195/sq.ft.      2
₹ 5,929/sq.ft.       2
₹ 8,283/sq.ft.       2
₹ 8,411/sq.ft.       2
₹ 9,950/sq.ft.       2
₹ 10,553/sq.ft.      2
₹ 9,742/sq.ft.       2
₹ 5,744/sq.ft.       2
₹ 8,294/sq.ft.       2
₹ 3,477/sq.ft.       2
₹ 8,814/sq.ft.       2
₹ 8,031/sq.ft.       2
₹ 9,550/sq.ft.       2
₹ 8,237/sq.ft.       2
₹ 14,615/sq.ft.      2
₹ 9,074/sq.ft.       2
₹ 7,765/sq.ft.       2
₹ 6,402/sq.ft.       2
₹ 9,020/sq.ft.       2
₹ 8,412/sq.ft.       2
₹ 8,835/sq.ft.       2
₹ 4,761/sq.ft.       2
₹ 6,465/sq.ft.       2
₹ 8,536/sq.ft.       2
₹ 19,000/sq.ft.      2
₹ 8,324/sq.ft.       2
₹ 14,285/sq.ft.      2
₹ 6,353/sq.ft.       2
₹ 6,406/sq.ft.       2
₹ 6,839/sq.ft.       2
₹ 7,716/sq.ft.       2
₹ 5,982/sq.ft.       2
₹ 8,024/sq.ft.       2
₹ 6,896/sq.ft.       2
₹ 6,153/sq.ft.       2
₹ 9,306/sq.ft.       2
₹ 16,363/sq.ft.      2
₹ 13,709/sq.ft.      2
₹ 8,457/sq.ft.       2
₹ 5,454/sq.ft.       2
₹ 8,424/sq.ft.       2
₹ 7,987/sq.ft.       2
₹ 6,382/sq.ft.       2
₹ 14,683/sq.ft.      2
₹ 14,303/sq.ft.      2
₹ 5,177/sq.ft.       2
₹ 8,305/sq.ft.       2
₹ 9,589/sq.ft.       2
₹ 5,564/sq.ft.       2
₹ 6,243/sq.ft.       2
₹ 5,980/sq.ft.       2
₹ 5,828/sq.ft.       2
₹ 8,518/sq.ft.       2
₹ 6,588/sq.ft.       2
₹ 8,756/sq.ft.       2
₹ 9,482/sq.ft.       2
₹ 5,599/sq.ft.       2
₹ 4,745/sq.ft.       2
₹ 9,022/sq.ft.       2
₹ 12,012/sq.ft.      2
₹ 7,185/sq.ft.       2
₹ 16,858/sq.ft.      2
₹ 8,166/sq.ft.       2
₹ 7,631/sq.ft.       2
₹ 11,726/sq.ft.      2
₹ 9,263/sq.ft.       2
₹ 6,189/sq.ft.       2
₹ 58/sq.ft.          2
₹ 5,463/sq.ft.       2
₹ 10,370/sq.ft.      2
₹ 4,000/sq.ft.       2
₹ 5,899/sq.ft.       2
₹ 11,333/sq.ft.      2
₹ 9,259/sq.ft.       2
₹ 10,384/sq.ft.      2
₹ 10,526/sq.ft.      2
₹ 8,582/sq.ft.       2
₹ 8,310/sq.ft.       2
₹ 7,530/sq.ft.       2
₹ 8,006/sq.ft.       2
₹ 13,769/sq.ft.      2
₹ 8,609/sq.ft.       2
₹ 8,524/sq.ft.       2
₹ 9,600/sq.ft.       2
₹ 7,574/sq.ft.       2
₹ 7,225/sq.ft.       2
₹ 11,700/sq.ft.      2
₹ 6,551/sq.ft.       2
₹ 9,677/sq.ft.       2
₹ 8,720/sq.ft.       2
₹ 6,318/sq.ft.       2
₹ 11,627/sq.ft.      2
₹ 6,569/sq.ft.       2
₹ 11,529/sq.ft.      2
₹ 6,217/sq.ft.       2
₹ 9,062/sq.ft.       2
₹ 9,449/sq.ft.       2
₹ 8,053/sq.ft.       2
₹ 8,618/sq.ft.       2
₹ 6,686/sq.ft.       2
₹ 8,972/sq.ft.       2
₹ 5,111/sq.ft.       2
₹ 5,786/sq.ft.       2
₹ 6,985/sq.ft.       2
₹ 12,777/sq.ft.      2
₹ 8,517/sq.ft.       2
₹ 9,452/sq.ft.       2
₹ 6,927/sq.ft.       2
₹ 6,190/sq.ft.       2
₹ 6,206/sq.ft.       2
₹ 15,294/sq.ft.      2
₹ 9,978/sq.ft.       2
₹ 3,695/sq.ft.       2
₹ 11,992/sq.ft.      2
₹ 5,658/sq.ft.       2
₹ 7,758/sq.ft.       2
₹ 7,863/sq.ft.       2
₹ 11,250/sq.ft.      2
₹ 4,307/sq.ft.       2
₹ 8,974/sq.ft.       2
₹ 8,670/sq.ft.       2
₹ 8,159/sq.ft.       2
₹ 7,058/sq.ft.       2
₹ 11,715/sq.ft.      2
₹ 7,174/sq.ft.       2
₹ 6,938/sq.ft.       2
₹ 5,671/sq.ft.       2
₹ 19,882/sq.ft.      2
₹ 9,791/sq.ft.       2
₹ 9,620/sq.ft.       2
₹ 7,097/sq.ft.       2
₹ 7,490/sq.ft.       2
₹ 6,076/sq.ft.       2
₹ 15,500/sq.ft.      2
₹ 5,150/sq.ft.       2
₹ 6,428/sq.ft.       2
₹ 5,100/sq.ft.       2
₹ 5,517/sq.ft.       2
₹ 9,025/sq.ft.       2
₹ 6,373/sq.ft.       2
₹ 18,271/sq.ft.      2
₹ 8,252/sq.ft.       2
₹ 16,985/sq.ft.      2
₹ 6,422/sq.ft.       2
₹ 4,909/sq.ft.       2
₹ 8,897/sq.ft.       2
₹ 4,327/sq.ft.       2
₹ 15,263/sq.ft.      2
₹ 16,747/sq.ft.      2
₹ 8,290/sq.ft.       2
₹ 8,519/sq.ft.       2
₹ 3,911/sq.ft.       2
₹ 6,333/sq.ft.       2
₹ 6,315/sq.ft.       2
₹ 6,053/sq.ft.       2
₹ 4,856/sq.ft.       2
₹ 5,056/sq.ft.       2
₹ 14,237/sq.ft.      2
₹ 8,433/sq.ft.       2
₹ 20,687/sq.ft.      2
₹ 12,212/sq.ft.      2
₹ 13,108/sq.ft.      2
₹ 15,551/sq.ft.      2
₹ 15,416/sq.ft.      2
₹ 9,743/sq.ft.       2
₹ 5,839/sq.ft.       2
₹ 11,765/sq.ft.      2
₹ 17,039/sq.ft.      2
₹ 8,846/sq.ft.       2
₹ 14,785/sq.ft.      2
₹ 12,022/sq.ft.      2
₹ 13,270/sq.ft.      2
₹ 19,767/sq.ft.      2
₹ 11,336/sq.ft.      2
₹ 7,908/sq.ft.       2
₹ 9,007/sq.ft.       2
₹ 8,733/sq.ft.       2
₹ 9,672/sq.ft.       2
₹ 9,797/sq.ft.       2
₹ 9,922/sq.ft.       2
₹ 7,359/sq.ft.       2
₹ 8,600/sq.ft.       2
₹ 8,453/sq.ft.       2
₹ 13,430/sq.ft.      2
₹ 16,608/sq.ft.      2
₹ 5,649/sq.ft.       2
₹ 21,538/sq.ft.      2
₹ 9,854/sq.ft.       2
₹ 11,125/sq.ft.      2
₹ 13,991/sq.ft.      2
₹ 8,279/sq.ft.       2
₹ 200,000/sq.ft.     2
₹ 5,528/sq.ft.       2
₹ 8,903/sq.ft.       2
₹ 6,811/sq.ft.       2
₹ 6,209/sq.ft.       2
₹ 5,284/sq.ft.       2
₹ 5,614/sq.ft.       2
₹ 6,616/sq.ft.       2
₹ 6,702/sq.ft.       2
₹ 5,291/sq.ft.       2
₹ 5,189/sq.ft.       2
₹ 10,666/sq.ft.      2
₹ 7,200/sq.ft.       2
₹ 33,198/sq.ft.      2
₹ 4,400/sq.ft.       2
₹ 5,470/sq.ft.       2
₹ 6,178/sq.ft.       2
₹ 5,204/sq.ft.       1
₹ 6,269/sq.ft.       1
₹ 7,860/sq.ft.       1
₹ 16,885/sq.ft.      1
₹ 9,767/sq.ft.       1
₹ 5,587/sq.ft.       1
₹ 6,940/sq.ft.       1
₹ 16,859/sq.ft.      1
₹ 14,084/sq.ft.      1
₹ 11,475/sq.ft.      1
₹ 9,156/sq.ft.       1
₹ 12,855/sq.ft.      1
₹ 7,910/sq.ft.       1
₹ 18,331/sq.ft.      1
₹ 24,300/sq.ft.      1
₹ 12,784/sq.ft.      1
₹ 26,936/sq.ft.      1
₹ 10,156/sq.ft.      1
₹ 7,194/sq.ft.       1
₹ 5,769/sq.ft.       1
₹ 8,866/sq.ft.       1
₹ 5,403/sq.ft.       1
₹ 6,378/sq.ft.       1
₹ 3,571/sq.ft.       1
₹ 7,581/sq.ft.       1
₹ 10,005/sq.ft.      1
₹ 7,410/sq.ft.       1
₹ 6,400/sq.ft.       1
₹ 4,715/sq.ft.       1
₹ 9,872/sq.ft.       1
₹ 6,594/sq.ft.       1
₹ 5,007/sq.ft.       1
₹ 6,376/sq.ft.       1
₹ 8,863/sq.ft.       1
₹ 4,320/sq.ft.       1
₹ 10,410/sq.ft.      1
₹ 5,178/sq.ft.       1
₹ 4,744/sq.ft.       1
₹ 9,406/sq.ft.       1
₹ 12,505/sq.ft.      1
₹ 11,153/sq.ft.      1
₹ 79/sq.ft.          1
₹ 3,768/sq.ft.       1
₹ 17,200/sq.ft.      1
₹ 6,615/sq.ft.       1
₹ 3,166/sq.ft.       1
₹ 9,838/sq.ft.       1
₹ 13,957/sq.ft.      1
₹ 8,768/sq.ft.       1
₹ 6,600/sq.ft.       1
₹ 11,738/sq.ft.      1
₹ 14,492/sq.ft.      1
₹ 12,800/sq.ft.      1
₹ 7,800/sq.ft.       1
₹ 15,590/sq.ft.      1
₹ 9,849/sq.ft.       1
₹ 11,482/sq.ft.      1
₹ 17,617/sq.ft.      1
₹ 6,106/sq.ft.       1
₹ 7,739/sq.ft.       1
₹ 16,030/sq.ft.      1
₹ 7/sq.ft.           1
₹ 9,955/sq.ft.       1
₹ 10,589/sq.ft.      1
₹ 6,443/sq.ft.       1
₹ 12,744/sq.ft.      1
₹ 9,285/sq.ft.       1
₹ 7,149/sq.ft.       1
₹ 13,115/sq.ft.      1
₹ 7,909/sq.ft.       1
₹ 12,920/sq.ft.      1
₹ 7,106/sq.ft.       1
₹ 5,883/sq.ft.       1
₹ 6,806/sq.ft.       1
₹ 9,502/sq.ft.       1
₹ 6,700/sq.ft.       1
₹ 5,750/sq.ft.       1
₹ 12,526/sq.ft.      1
₹ 12,244/sq.ft.      1
₹ 7,424/sq.ft.       1
₹ 10,361/sq.ft.      1
₹ 13,600/sq.ft.      1
₹ 5,308/sq.ft.       1
₹ 14,444/sq.ft.      1
₹ 7,188/sq.ft.       1
₹ 10,828/sq.ft.      1
₹ 15,664/sq.ft.      1
₹ 13,496/sq.ft.      1
₹ 9,463/sq.ft.       1
₹ 7,963/sq.ft.       1
₹ 12,185/sq.ft.      1
₹ 7,444/sq.ft.       1
₹ 6,345/sq.ft.       1
₹ 6,703/sq.ft.       1
₹ 6,150/sq.ft.       1
₹ 12,106/sq.ft.      1
₹ 13,074/sq.ft.      1
₹ 8,081/sq.ft.       1
₹ 13,136/sq.ft.      1
₹ 4,731/sq.ft.       1
₹ 5,142/sq.ft.       1
₹ 4,258/sq.ft.       1
₹ 17,441/sq.ft.      1
₹ 12,619/sq.ft.      1
₹ 4,546/sq.ft.       1
₹ 15,003/sq.ft.      1
₹ 3,970/sq.ft.       1
₹ 5,067/sq.ft.       1
₹ 14,118/sq.ft.      1
₹ 2,700/sq.ft.       1
₹ 18,492/sq.ft.      1
₹ 7,643/sq.ft.       1
₹ 16,923/sq.ft.      1
₹ 3,975/sq.ft.       1
₹ 4,705/sq.ft.       1
₹ 6,225/sq.ft.       1
₹ 17,990/sq.ft.      1
₹ 17,997/sq.ft.      1
₹ 18,477/sq.ft.      1
₹ 14,168/sq.ft.      1
₹ 7,036/sq.ft.       1
₹ 6,790/sq.ft.       1
₹ 5,420/sq.ft.       1
₹ 11,716/sq.ft.      1
₹ 12,181/sq.ft.      1
₹ 7,455/sq.ft.       1
₹ 7,032/sq.ft.       1
₹ 5,548/sq.ft.       1
₹ 5,888/sq.ft.       1
₹ 6,734/sq.ft.       1
₹ 9,024/sq.ft.       1
₹ 15,980/sq.ft.      1
₹ 28,000/sq.ft.      1
₹ 14,335/sq.ft.      1
₹ 15,793/sq.ft.      1
₹ 26,562/sq.ft.      1
₹ 6,300/sq.ft.       1
₹ 7,777/sq.ft.       1
₹ 14,100/sq.ft.      1
₹ 5,892/sq.ft.       1
₹ 10,158/sq.ft.      1
₹ 3,648/sq.ft.       1
₹ 7,772/sq.ft.       1
₹ 6,862/sq.ft.       1
₹ 13,969/sq.ft.      1
₹ 10,945/sq.ft.      1
₹ 13,269/sq.ft.      1
₹ 7,510/sq.ft.       1
₹ 8,514/sq.ft.       1
₹ 4,599/sq.ft.       1
₹ 14,110/sq.ft.      1
₹ 33,209/sq.ft.      1
₹ 14,202/sq.ft.      1
₹ 17,000/sq.ft.      1
₹ 15,240/sq.ft.      1
₹ 19,363/sq.ft.      1
₹ 5,832/sq.ft.       1
₹ 9,777/sq.ft.       1
₹ 8,160/sq.ft.       1
₹ 9,334/sq.ft.       1
₹ 5,897/sq.ft.       1
₹ 7,725/sq.ft.       1
₹ 10,895/sq.ft.      1
₹ 11,845/sq.ft.      1
₹ 23,401/sq.ft.      1
₹ 15,681/sq.ft.      1
₹ 7,539/sq.ft.       1
₹ 14,376/sq.ft.      1
₹ 9,221/sq.ft.       1
₹ 14,516/sq.ft.      1
₹ 19,200/sq.ft.      1
₹ 8,047/sq.ft.       1
₹ 4,888/sq.ft.       1
₹ 10,007/sq.ft.      1
₹ 13,765/sq.ft.      1
₹ 9,740/sq.ft.       1
₹ 9,552/sq.ft.       1
₹ 18,571/sq.ft.      1
₹ 14,500/sq.ft.      1
₹ 6,509/sq.ft.       1
₹ 11,426/sq.ft.      1
₹ 11,938/sq.ft.      1
₹ 12,318/sq.ft.      1
₹ 8,510/sq.ft.       1
₹ 12,810/sq.ft.      1
₹ 14,938/sq.ft.      1
₹ 6,709/sq.ft.       1
₹ 10,769/sq.ft.      1
₹ 8,087/sq.ft.       1
₹ 10,378/sq.ft.      1
₹ 13,696/sq.ft.      1
₹ 7,267/sq.ft.       1
₹ 11,832/sq.ft.      1
₹ 11,903/sq.ft.      1
₹ 4,881/sq.ft.       1
₹ 4,259/sq.ft.       1
₹ 11,185/sq.ft.      1
₹ 15,575/sq.ft.      1
₹ 7,804/sq.ft.       1
₹ 9,895/sq.ft.       1
₹ 17,455/sq.ft.      1
₹ 17,777/sq.ft.      1
₹ 12,312/sq.ft.      1
₹ 11,584/sq.ft.      1
₹ 5,011/sq.ft.       1
₹ 13,266/sq.ft.      1
₹ 7,600/sq.ft.       1
₹ 9,490/sq.ft.       1
₹ 9,558/sq.ft.       1
₹ 28,266/sq.ft.      1
₹ 7,869/sq.ft.       1
₹ 13,495/sq.ft.      1
₹ 18,400/sq.ft.      1
₹ 17,721/sq.ft.      1
₹ 5,530/sq.ft.       1
₹ 16,060/sq.ft.      1
₹ 12,346/sq.ft.      1
₹ 7,674/sq.ft.       1
₹ 14,871/sq.ft.      1
₹ 11,121/sq.ft.      1
₹ 16,486/sq.ft.      1
₹ 21,360/sq.ft.      1
₹ 26,790/sq.ft.      1
₹ 7,220/sq.ft.       1
₹ 12,627/sq.ft.      1
₹ 7,392/sq.ft.       1
₹ 12,818/sq.ft.      1
₹ 16,050/sq.ft.      1
₹ 18,500/sq.ft.      1
₹ 5,505/sq.ft.       1
₹ 13,125/sq.ft.      1
₹ 5,788/sq.ft.       1
₹ 13,690/sq.ft.      1
₹ 8,051/sq.ft.       1
₹ 28,101/sq.ft.      1
₹ 7,260/sq.ft.       1
₹ 14,950/sq.ft.      1
₹ 9,783/sq.ft.       1
₹ 12,544/sq.ft.      1
₹ 12,235/sq.ft.      1
₹ 14,079/sq.ft.      1
₹ 6,713/sq.ft.       1
₹ 13,790/sq.ft.      1
₹ 10,814/sq.ft.      1
₹ 12,140/sq.ft.      1
₹ 15,160/sq.ft.      1
₹ 6,661/sq.ft.       1
₹ 6,163/sq.ft.       1
₹ 10,901/sq.ft.      1
₹ 4,193/sq.ft.       1
₹ 3,309/sq.ft.       1
₹ 15,906/sq.ft.      1
₹ 11,294/sq.ft.      1
₹ 11,204/sq.ft.      1
₹ 11,470/sq.ft.      1
₹ 10,567/sq.ft.      1
₹ 12,788/sq.ft.      1
₹ 6,826/sq.ft.       1
₹ 9,528/sq.ft.       1
₹ 15,514/sq.ft.      1
₹ 14,563/sq.ft.      1
₹ 9,212/sq.ft.       1
₹ 6,888/sq.ft.       1
₹ 11,174/sq.ft.      1
₹ 10,841/sq.ft.      1
₹ 5,717/sq.ft.       1
₹ 5,867/sq.ft.       1
₹ 14,177/sq.ft.      1
₹ 10,174/sq.ft.      1
₹ 7,646/sq.ft.       1
₹ 6,961/sq.ft.       1
₹ 4,528/sq.ft.       1
₹ 8,580/sq.ft.       1
₹ 13,571/sq.ft.      1
₹ 11,686/sq.ft.      1
₹ 6,585/sq.ft.       1
₹ 7,230/sq.ft.       1
₹ 6,453/sq.ft.       1
₹ 5,973/sq.ft.       1
₹ 15,185/sq.ft.      1
₹ 12,152/sq.ft.      1
₹ 13,253/sq.ft.      1
₹ 12,190/sq.ft.      1
₹ 4,370/sq.ft.       1
₹ 4,355/sq.ft.       1
₹ 7,734/sq.ft.       1
₹ 5,418/sq.ft.       1
₹ 11,358/sq.ft.      1
₹ 12,599/sq.ft.      1
₹ 13,678/sq.ft.      1
₹ 5,004/sq.ft.       1
₹ 4,836/sq.ft.       1
₹ 10,595/sq.ft.      1
₹ 8,646/sq.ft.       1
₹ 10,461/sq.ft.      1
₹ 10,080/sq.ft.      1
₹ 8,172/sq.ft.       1
₹ 12,571/sq.ft.      1
₹ 11,914/sq.ft.      1
₹ 14,983/sq.ft.      1
₹ 8,759/sq.ft.       1
₹ 8,839/sq.ft.       1
₹ 16,750/sq.ft.      1
₹ 16,580/sq.ft.      1
₹ 10,334/sq.ft.      1
₹ 9,266/sq.ft.       1
₹ 11,860/sq.ft.      1
₹ 9,051/sq.ft.       1
₹ 9,622/sq.ft.       1
₹ 13,528/sq.ft.      1
₹ 4,864/sq.ft.       1
₹ 5,499/sq.ft.       1
₹ 7,065/sq.ft.       1
₹ 9,980/sq.ft.       1
₹ 9,036/sq.ft.       1
₹ 13,888/sq.ft.      1
₹ 13,878/sq.ft.      1
₹ 14,557/sq.ft.      1
₹ 12,325/sq.ft.      1
₹ 9,133/sq.ft.       1
₹ 6,819/sq.ft.       1
₹ 17,285/sq.ft.      1
₹ 13,929/sq.ft.      1
₹ 6,514/sq.ft.       1
₹ 6,580/sq.ft.       1
₹ 6,708/sq.ft.       1
₹ 13,846/sq.ft.      1
₹ 13,875/sq.ft.      1
₹ 12,400/sq.ft.      1
₹ 7,146/sq.ft.       1
₹ 14,074/sq.ft.      1
₹ 11,739/sq.ft.      1
₹ 12,110/sq.ft.      1
₹ 14,623/sq.ft.      1
₹ 6,523/sq.ft.       1
₹ 21,013/sq.ft.      1
₹ 7,437/sq.ft.       1
₹ 4,022/sq.ft.       1
₹ 3,935/sq.ft.       1
₹ 9,387/sq.ft.       1
₹ 9,117/sq.ft.       1
₹ 10,953/sq.ft.      1
₹ 11,052/sq.ft.      1
₹ 14,536/sq.ft.      1

In [219]:
data.drop(index=2849, inplace=True)

In [220]:
data.reset_index(drop=True, inplace=True)

In [221]:
# data['price_per_sqft'] = (
#     data['price_per_sqft']
#     .str.extract(r'([0-9,]+)')[0]
#     .str.replace(',', '', regex=False)
#     .astype('float')
# )

data['price_per_sqft'] = (
    data['price_per_sqft']
    .str.split('/').str.get(0)
    .str.replace('₹', '', regex=False)
    .str.replace(',', '', regex=False)
    .str.strip()
    .astype('float')
)

In [222]:
# bedRoom
data['bedRoom'].value_counts()

bedRoom
3 Bedrooms    1437
2 Bedrooms     944
4 Bedrooms     478
1 Bedroom      104
5 Bedrooms      31
6 Bedrooms       3
Name: count, dtype: int64

In [223]:
data[data['bedRoom'].isnull()]

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
2841,4 BHK Flat in Sector 53 Gurgaon,tulip monsella,NaN,33198.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2842,2 BHK Flat in New Palam Vihar,my home,NaN,4400.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2843,2 BHK Flat in Sohna,breez global hill view,NaN,5470.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2913,3 BHK Flat in Sector 99A Gurgaon,pareena coban residences,NaN,5759.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2914,1 BHK Flat in Golf Course Ext Road,ikon tower baani city centre,NaN,12437.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2915,2 BHK Flat in Sector 89 Gurgaon,greenopolis,NaN,4820.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2917,4 BHK Flat in C Block Sushant Lok Phase 1,maple heights,NaN,8888.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2918,2 BHK Flat in Sector 99 Gurgaon,assotech blith,NaN,6593.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [224]:
# Drop all rows

data = data[~data['bedRoom'].isnull()]
data['bedRoom'].isnull().sum()

np.int64(0)

In [230]:
data['bedRoom'] = data['bedRoom'].str.split(' ').str.get(0).astype('int')
data.head()

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,5000.0,Carpet area: 900 (83.61 sq.m.),2,2 Bathrooms,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,apna enclave,0.50,7692.0,Carpet area: 650 (60.39 sq.m.),2,2 Bathrooms,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,tulsiani easy in homes,0.40,6722.0,Carpet area: 595 (55.28 sq.m.),2,2 Bathrooms,3 Balconies,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,smart world orchard,1.47,12250.0,Carpet area: 1200 (111.48 sq.m.),2,2 Bathrooms,2 Balconies,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,parkwood westend,0.70,5204.0,Super Built up area 1345(124.95 sq.m.),2,2 Bathrooms,3 Balconies,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [ ]:
# bathroom
data['bathroom'].value_counts()

bathroom
2 Bathrooms    1044
3 Bathrooms     989
4 Bathrooms     636
5 Bathrooms     169
1 Bathroom      112
6 Bathrooms      42
7 Bathrooms       5
Name: count, dtype: int64

In [ ]:
data['bathroom'].isnull().sum()

np.int64(0)

In [231]:
data['bathroom'] = data['bathroom'].str.split(' ').str.get(0).astype('int')
data.head()

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,5000.0,Carpet area: 900 (83.61 sq.m.),2,2,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,apna enclave,0.50,7692.0,Carpet area: 650 (60.39 sq.m.),2,2,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,tulsiani easy in homes,0.40,6722.0,Carpet area: 595 (55.28 sq.m.),2,2,3 Balconies,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,smart world orchard,1.47,12250.0,Carpet area: 1200 (111.48 sq.m.),2,2,2 Balconies,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,parkwood westend,0.70,5204.0,Super Built up area 1345(124.95 sq.m.),2,2,3 Balconies,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [ ]:
data['balcony'].value_counts()

balcony
3     974
3+    862
2     749
1     315
No     97
Name: count, dtype: int64

In [232]:
# balcony
data['balcony'].isnull().sum() # 0

data['balcony'] = data['balcony'].str.split(' ').str.get(0).str.replace('No','0')
data['balcony'].value_counts()

balcony
3     974
3+    862
2     749
1     315
0      97
Name: count, dtype: int64

In [ ]:
# additionalRoom
data['additionalRoom'].fillna('NA', inplace=True) # NA -> Not Available

C:\Users\bhave\AppData\Local\Temp\ipykernel_23208\1508091792.py:2: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  data['additionalRoom'].fillna('NA', inplace=True) # NA -> Not Available

0                                                  NA
1                                                  NA
2                                                  NA
3                                          Study Room
4                                          Study Room
5                                                  NA
6                                                  NA
7                                                  NA
8                                          Study Room
9                                        Servant Room
10                                                 NA
11                                                 NA
12                                                 NA
13                                                 NA
14                                         Study Room
15                                                 NA
16                                                 NA
17                                                 NA
18                                                 NA
19                                       Servant Room
20                                         Study Room
21                                       Servant Room
22                                                 NA
23                                       Servant Room
24                                       Servant Room
25                                                 NA
26                                                 NA
27                                       Servant Room
28                                                 NA
29                                                 NA
30                                                 NA
31                                         Pooja Room
32                                                 NA
33                                                 NA
34                                                 NA
35                                             Others
36                                       Servant Room
37                                                 NA
38                                                 NA
39                                       Servant Room
40                                                 NA
41                                       Servant Room
42                                       Servant Room
43                                                 NA
44                                                 NA
45                            Pooja Room,Servant Room
46                                                 NA
47                                                 NA
48                                       Servant Room
49                            Study Room,Servant Room
50                                                 NA
51                                         Study Room
52                                                 NA
53                                                 NA
54                                                 NA
55                                                 NA
56                                                 NA
57                                       Servant Room
58                                             Others
59                                         Store Room
60                                         Study Room
61                                       Servant Room
62                                                 NA
63                                                 NA
64                                                 NA
65                                                 NA
66                                                 NA
67                                                 NA
68                                                 NA
69                                                 NA
70                                                 NA
71                                                 NA
72                                                 NA
73                                       Servant Room
74                                                 NA
75                                                 NA
76                                                 NA
77                                                 NA
78                                       Servant Room
79                                                 NA
80                                                 NA
81                                                 NA
82                                       Servant Room
83                                                 NA
84                                                 NA
85                                       Servant Room
86                                                 NA
87                                                 NA
88                                             Others
89                                                 NA
90                                                 NA
91                                                 NA
92                                                 NA
93                                                 NA
94                                                 NA
95                                                 NA
96                                                 NA
97                                                 NA
98                                                 NA
99                                  Study Room,Others
100                                                NA
101                                                NA
102                                        Study Room
103                                                NA
104                                      Servant Room
105                                      Servant Room
106                                                NA
107                                            Others
108                                                NA
109                                                NA
110                                                NA
111                                                NA
112                                                NA
113                                                NA
114                                                NA
115                                                NA
116                                                NA
117                Pooja Room,Study Room,Servant Room
118                                        Pooja Room
119                                                NA
120                                                NA
121                                                NA
122                                 Study Room,Others
123                                                NA
124                                                NA
125                                                NA
126                                                NA
127                                                NA
128                                                NA
129                                                NA
130                                                NA
131                                                NA
132                                                NA
133                                                NA
134                                                NA
135                           Pooja Room,Servant Room
136                             Pooja Room,Study Room
137                                                NA
138                                        Study Room
139                                      Servant Room
140                                                NA
141                                                NA
142                Study Room,Servant Room,Store Room
143                    Study Room,Servant Room,Others
144                             Pooja Room,Store Room
145                                                NA
146                                                NA
147                                                NA
148                                        Study Room
149                                                NA
150                                                NA
151                                                NA
152                                                NA
153                                                NA
154                                                NA
155                                                NA
156                                                NA
157                                                NA
158                                                NA
159                                                NA
160                                        Study Room
161                                                NA
162                                                NA
163                                                NA
164                                        Store Room
165                                                NA
166                                                NA
167                                        Study Room
168                                            Others
169                                                NA
170                                                NA
171                                                NA
172                                        Study Room
173                                                NA
174                                      Servant Room
175                Pooja Room,Study Room,Servant Room
176                                      Servant Room
177                                                NA
178                                                NA
179                                                NA
180                                                NA
181                                                NA
182                                                NA
183                                                NA
184                                                NA
185                                                NA
186                                                NA
187                                                NA
188                                                NA
189                                                NA
190                                        Study Room
191                                                NA
192                           Study Room,Servant Room
193                                            Others
194                                                NA
195                                                NA
196                                                NA
197                                                NA
198                                                NA
199                                                NA
200                                                NA
201                                                NA
202                                                NA
203                                        Pooja Room
204                                                NA
205                                                NA
206                                                NA
207                                        Study Room
208                                                NA
209                                                NA
210                                                NA
211                                            Others
212                                                NA
213                                                NA
214                Study Room,Servant Room,Store Room
215                                        Study Room
216                                                NA
217                                      Servant Room
218                           Pooja Room,Servant Room
219                                                NA
220                                                NA
221                                                NA
222                                                NA
223                                            Others
224                                                NA
225                                                NA
226                                            Others
227                                            Others
228                                            Others
229                                                NA
230                                                NA
231                                                NA
232                                        Study Room
233                                                NA
234                                                NA
235                                                NA
236                                      Servant Room
237                                                NA
238                                 Study Room,Others
239                                                NA
240                                      Servant Room
241                                                NA
242                                                NA
243                                                NA
244                                      Servant Room
245                                                NA
246                                                NA
247                                        Study Room
248                                                NA
249                                      Servant Room
250                                                NA
251                                                NA
252                                                NA
253                                                NA
254                                        Study Room
255                    Servant Room,Others,Pooja Room
256                                                NA
257                                                NA
258                               Servant Room,Others
259                                                NA
260                                      Servant Room
261                               Servant Room,Others
262                                                NA
263                                                NA
264                                                NA
265                                                NA
266                                                NA
267                                                NA
268                                            Others
269                                                NA
270                                                NA
271                                                NA
272                                                NA
273                                                NA
274                                                NA
275                                            Others
276                                                NA
277                                                NA
278                                                NA
279                                                NA
280                                                NA
281                                                NA
282                                                NA
283                                                NA
284                                      Servant Room
285                           Study Room,Servant Room
286                                        Study Room
287                                      Servant Room
288                                                NA
289                           Servant Room,Store Room
290                                      Servant Room
291                                                NA
292                                                NA
293                                      Servant Room
294                                                NA
295                                                NA
296                                                NA
297                                        Study Room
298                                                NA
299                                      Servant Room
300                                                NA
301                                      Servant Room
302                             Pooja Room,Study Room
303                  Pooja Room,Study Room,Store Room
304                               Servant Room,Others
305                                                NA
306                                      Servant Room
307                                      Servant Room
308                                                NA
309                                      Servant Room
310                                                NA
311                                                NA
312                                        Study Room
313                                      Servant Room
314                                      Servant Room
315                                                NA
316                                                NA
317                                            Others
318                                        Study Room
319                                      Servant Room
320                                                NA
321                           Servant Room,Store Room
322                                      Servant Room
323                                                NA
324                                                NA
325                                                NA
326                                      Servant Room
327                                                NA
328                                      Servant Room
329                             Pooja Room,Study Room
330                  Pooja Room,Study Room,Store Room
331                               Servant Room,Others
332                                                NA
333                                      Servant Room
334                                      Servant Room
335                                                NA
336                                      Servant Room
337                                      Servant Room
338                                                NA
339                                                NA
340                                      Servant Room
341                                            Others
342                           Study Room,Servant Room
343                                                NA
344                                        Study Room
345                                                NA
346         Pooja Room,Study Room,Servant Room,Others
347                                            Others
348                                      Servant Room
349                                                NA
350                                                NA
351                                                NA
352                                      Servant Room
353                           Study Room,Servant Room
354                                                NA
355                                        Study Room
356                                      Servant Room
357                                        Study Room
358                                      Servant Room
359                                      Servant Room
360                                      Servant Room
361                                      Servant Room
362                                                NA
363                                      Servant Room
364                           Pooja Room,Servant Room
365                           Pooja Room,Servant Room
366                                                NA
367                                                NA
368                Study Room,Servant Room,Store Room
369                                      Servant Room

In [238]:
data['additionalRoom'] = data['additionalRoom'].str.lower()
data.head()

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,5000.0,Carpet area: 900 (83.61 sq.m.),2,2,1,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,apna enclave,0.50,7692.0,Carpet area: 650 (60.39 sq.m.),2,2,1,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,tulsiani easy in homes,0.40,6722.0,Carpet area: 595 (55.28 sq.m.),2,2,3,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,smart world orchard,1.47,12250.0,Carpet area: 1200 (111.48 sq.m.),2,2,2,study room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,parkwood westend,0.70,5204.0,Super Built up area 1345(124.95 sq.m.),2,2,3,study room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."